INSERT INTO Athletes VALUES('1532872', 'ALEKSANYAN Artur', 'M', NULL, 'Armenia');
INSERT INTO Athletes VALUES('1532873', 'AMOYAN Malkhas', 'M', NULL, 'Armenia');
INSERT INTO Athletes VALUES('1532874', 'GALSTYAN Slavik', 'M', NULL, 'Armenia');
INSERT INTO Athletes VALUES('1532944', 'HARUTYUNYAN Arsen', 'M', NULL, 'Armenia');
INSERT INTO Athletes VALUES('1532945', 'TEVANYAN Vazgen', 'M', NULL, 'Armenia');
INSERT INTO Athletes VALUES('1532951', 'ARENAS Lorena', 'F', NULL, 'Colombia');
INSERT INTO Athletes VALUES('1533112', 'McKENZIE Ashley', 'M', NULL, 'Jamaica');
INSERT INTO Athletes VALUES('1533136', 'BASS BITTAYE Gina Mariam', 'F', NULL, 'Gambia');
INSERT INTO Athletes VALUES('1533176', 'CAMARA Ebrahima', 'M', NULL, 'Gambia');
INSERT INTO Athletes VALUES('1533188', 'RUEDA SANTOS Lizeth', 'F', NULL, 'Mexico');
INSERT INTO Athletes VALUES('1533189', 'TAPIA VIDAL Rosa Maria', 'F', NULL, 'Mexico');
INSERT INTO Athletes VALUES('1533190', 'GRAJALES Crisanto', 'M', NULL, 'Mexico');
INSERT INTO Athletes VALUES('1533208', 'MAAROUFOU Hachim', 'M', NULL, 'Comoros');
INSERT INTO Athletes VALUES('1533209', 'SAADI Maesha', 'F', NULL, 'Comoros');
INSERT INTO Athletes VALUES('1533230', 'DIOSDADO Nuria', 'F', NULL, 'Mexico');
INSERT INTO Athletes VALUES('1533231', 'JIMENEZ Joana', 'F', NULL, 'Mexico');
INSERT INTO Athletes VALUES('1533232', 'SOBRINO Jessica', 'F', NULL, 'Mexico');
INSERT INTO Athletes VALUES('1533234', 'ALFEREZ Regina', 'F', NULL, 'Mexico');
INSERT INTO Athletes VALUES('1533235', 'ARELLANO Fernanda', 'F', NULL, 'Mexico');
INSERT INTO Athletes VALUES('1533237', 'TOSCANO Pamela', 'F', NULL, 'Mexico');
INSERT INTO Athletes VALUES('1533239', 'GONZALEZ Itzamary', 'F', NULL, 'Mexico');
INSERT INTO Athletes VALUES('1533240', 'RODRIGUEZ Samanta', 'F', NULL, 'Mexico');
INSERT INTO Athletes VALUES('1533243', 'INZUNZA Glenda', 'F', NULL, 'Mexico');
INSERT INTO Athletes VALUES('1533245', 'SEHEN Sajjad', 'M', NULL, 'Iraq');
INSERT INTO Athletes VALUES('1533359', 'RUBAIAWI Ali Ammar Yusur', 'M', NULL, 'Iraq');
INSERT INTO Athletes VALUES('1533364', 'ISMAIL Mohamed', 'M', NULL, 'Djibouti');
INSERT INTO Athletes VALUES('1533371', 'HASSAN Ibrahim', 'M', NULL, 'Djibouti');
INSERT INTO Athletes VALUES('1533372', 'WAISS Abdi', 'M', NULL, 'Djibouti');
INSERT INTO Athletes VALUES('1533374', 'HASSAN NOUR Samiyah', 'F', NULL, 'Djibouti');
INSERT INTO Athletes VALUES('1533378', 'HOUSSEIN BARKAT Houmed', 'M', NULL, 'Djibouti');
INSERT INTO Athletes VALUES('1535180', 'BARAT Andy', 'M', NULL, 'Comoros');
INSERT INTO Athletes VALUES('1535186', 'MARTINEZ RAMIREZ Miguel Angel', 'M', NULL, 'Mexico');
INSERT INTO Athletes VALUES('1535187', 'VERDE ALVAREZ Marco Alonso', 'M', NULL, 'Mexico');
INSERT INTO Athletes VALUES('1535191', 'GONZALEZ Alegna', 'F', NULL, 'Mexico');
INSERT INTO Athletes VALUES('1535195', 'LOPEZ Jesus Tonatiu', 'M', NULL, 'Mexico');
INSERT INTO Athletes VALUES('1535199', 'PORTILLO Erick', 'M', NULL, 'Mexico');
INSERT INTO Athletes VALUES('1535201', 'MUNOZ Uziel', 'M', NULL, 'Mexico');
INSERT INTO Athletes VALUES('1535202', 'del REAL Diego', 'M', NULL, 'Mexico');
INSERT INTO Athletes VALUES('1535203', 'DOCTOR Jose Luis', 'M', NULL, 'Mexico');
INSERT INTO Athletes VALUES('1535212', 'MORAN Paola', 'F', NULL, 'Mexico');
INSERT INTO Athletes VALUES('1535214', 'GALVAN Laura', 'F', NULL, 'Mexico');
INSERT INTO Athletes VALUES('1535216', 'CORTES Alma Delia', 'F', NULL, 'Mexico');
INSERT INTO Athletes VALUES('1535217', 'CRISTIAN MOSCOTE Citlali', 'F', NULL, 'Mexico');
INSERT INTO Athletes VALUES('1535222', 'PALMA OLIVARES Ever Jair', 'M', NULL, 'Mexico');
INSERT INTO Athletes VALUES('1535225', 'OETLING RAMIREZ Elena', 'F', NULL, 'Mexico');
INSERT INTO Athletes VALUES('1535226', 'AGUILAR CHAVEZ PEON Mariana', 'F', NULL, 'Mexico');
INSERT INTO Athletes VALUES('1535252', 'LECHUGA ALANIS Kenia', 'F', NULL, 'Mexico');
INSERT INTO Athletes VALUES('1535260', 'LOPEZ GARCIA Alexis', 'M', NULL, 'Mexico');
INSERT INTO Athletes VALUES('1535267', 'CARBALLO NIETO Miguel', 'M', NULL, 'Mexico');
INSERT INTO Athletes VALUES('1535310', 'BLANCO Luisa', 'F', NULL, 'Colombia');
INSERT INTO Athletes VALUES('1535343', 'WILLARS VALDEZ Randal', 'M', NULL, 'Mexico');
INSERT INTO Athletes VALUES('1535345', 'BERLIN REYES Kevin', 'M', NULL, 'Mexico');
INSERT INTO Athletes VALUES('1535346', 'OROZCO LOZA Alejandra', 'F', NULL, 'Mexico');
INSERT INTO Athletes VALUES('1535348', 'AGUNDEZ GARCIA Gabriela', 'F', NULL, 'Mexico');
INSERT INTO Athletes VALUES('1535349', 'OLVERA IBARRA Osmar', 'M', NULL, 'Mexico');
INSERT INTO Athletes VALUES('1535350', 'GARZA PEREZ Eugenio', 'M', NULL, 'Mexico');
INSERT INTO Athletes VALUES('1535351', 'FERNANDEZ Federico', 'M', NULL, 'Mexico');
INSERT INTO Athletes VALUES('1535354', 'de LARA OJEDA Miguel Alejandro', 'M', NULL, 'Mexico');
INSERT INTO Athletes VALUES('1535356', 'MORENO Alexa', 'F', NULL, 'Mexico');
INSERT INTO Athletes VALUES('1535357', 'SANDOVAL Ahtziri', 'F', NULL, 'Mexico');
INSERT INTO Athletes VALUES('1535358', 'FLORES Sofia', 'F', NULL, 'Mexico');
INSERT INTO Athletes VALUES('1535359', 'SALAZAR Kimberly', 'F', NULL, 'Mexico');
INSERT INTO Athletes VALUES('1535360', 'TEJEDA Adirem', 'F', NULL, 'Mexico');
INSERT INTO Athletes VALUES('1535361', 'ALCOCER Dalia', 'F', NULL, 'Mexico');
INSERT INTO Athletes VALUES('1535362', 'GUTIERREZ Julia', 'F', NULL, 'Mexico');
INSERT INTO Athletes VALUES('1535363', 'HERNANDEZ Emiliano', 'M', NULL, 'Mexico');
INSERT INTO Athletes VALUES('1535364', 'CARRILLO Duilio', 'M', NULL, 'Mexico');
INSERT INTO Athletes VALUES('1535365', 'OLIVER Mayan', 'F', NULL, 'Mexico');
INSERT INTO Athletes VALUES('1535366', 'SANSORES Carlos', 'M', NULL, 'Mexico');
INSERT INTO Athletes VALUES('1535367', 'SOUZA Daniela Paola', 'F', NULL, 'Mexico');
INSERT INTO Athletes VALUES('1535368', 'CLELAND QUINONEZ Alan', 'M', NULL, 'Mexico');
INSERT INTO Athletes VALUES('1535373', 'GRIGORIAN Aram', 'M', NULL, 'UA Emirates');
INSERT INTO Athletes VALUES('1535374', 'KOSTOEV Dzhafar', 'M', NULL, 'UA Emirates');
INSERT INTO Athletes VALUES('1535375', 'MAGOMEDOMAROV Magomedomar', 'M', NULL, 'UA Emirates');
INSERT INTO Athletes VALUES('1535376', 'TATALASHVILI Nugzari', 'M', NULL, 'UA Emirates');
INSERT INTO Athletes VALUES('1535383', 'BISHRELT Khorloodoi', 'F', NULL, 'UA Emirates');
INSERT INTO Athletes VALUES('1535385', 'HOUSSEIN Alexandre', 'M', NULL, 'Djibouti');
INSERT INTO Athletes VALUES('1535395', 'AL SAYEGH Safia', 'F', NULL, 'UA Emirates');
INSERT INTO Athletes VALUES('1535420', 'VALENCIA Alejandra', 'F', NULL, 'Mexico');
INSERT INTO Athletes VALUES('1535429', 'RUIZ Angela', 'F', NULL, 'Mexico');
INSERT INTO Athletes VALUES('1535430', 'GRANDE Matias', 'M', NULL, 'Mexico');
INSERT INTO Athletes VALUES('1535433', 'PRIETO Marcela', 'F', NULL, 'Mexico');
INSERT INTO Athletes VALUES('1535438', 'RAMIREZ RAMOS Edson Ismael', 'M', NULL, 'Mexico');
INSERT INTO Athletes VALUES('1535439', 'RODRIGUEZ Gabriela', 'F', NULL, 'Mexico');
INSERT INTO Athletes VALUES('1535440', 'ZAVALA VAZQUEZ Alejandra', 'F', NULL, 'Mexico');
INSERT INTO Athletes VALUES('1535441', 'QUEZADA MARQUEZ Carlos', 'M', NULL, 'Mexico');
INSERT INTO Athletes VALUES('1535442', 'PENAFLOR MOYSEN Aram Michell', 'M', NULL, 'Mexico');
INSERT INTO Athletes VALUES('1535444', 'REINOSO Sofia', 'F', NULL, 'Mexico');
INSERT INTO Athletes VALUES('1535448', 'BRIONES FRAGOZA Beatriz', 'F', NULL, 'Mexico');
INSERT INTO Athletes VALUES('1535449', 'ALANIS MORALES Karina', 'F', NULL, 'Mexico');
INSERT INTO Athletes VALUES('1535505', 'LINARES Natalia', 'F', NULL, 'Colombia');
INSERT INTO Athletes VALUES('1535506', 'LONGA Ronal', 'M', NULL, 'Colombia');
INSERT INTO Athletes VALUES('1535511', 'RUIZ HURTADO Flor Denis', 'F', NULL, 'Colombia');
INSERT INTO Athletes VALUES('1535512', 'ORJUELA Angie', 'F', NULL, 'Colombia');
INSERT INTO Athletes VALUES('1535513', 'RENTERIA RENTERIA Tatiana', 'F', NULL, 'Colombia');
INSERT INTO Athletes VALUES('1535514', 'VALDES PANA Angie Paola', 'F', NULL, 'Colombia');
INSERT INTO Athletes VALUES('1535522', 'ARBOLEDA MENDOZA Valeria', 'F', NULL, 'Colombia');
INSERT INTO Athletes VALUES('1535524', 'BOLANOS LOPEZ Victor', 'M', NULL, 'Colombia');
INSERT INTO Athletes VALUES('1535609', 'ABDOLI Samyar', 'M', NULL, 'IR Iran');
INSERT INTO Athletes VALUES('1535660', 'SIMWAKA Asimenye', 'F', NULL, 'Malawi');
INSERT INTO Athletes VALUES('1535693', 'AL MARZOOQI Omar Abdul Aziz', 'M', NULL, 'UA Emirates');
INSERT INTO Athletes VALUES('1535729', 'SERRANO Franco', 'M', NULL, 'Argentina');
INSERT INTO Athletes VALUES('1535766', 'KUMEL SAADI', 'M', NULL, 'Iraq');
INSERT INTO Athletes VALUES('1535776', 'JOSEF AL IMAM', 'M', NULL, 'Iraq');
INSERT INTO Athletes VALUES('1535804', 'MUNTADHER ABDULAMEER', 'M', NULL, 'Iraq');
INSERT INTO Athletes VALUES('1535805', 'MUNTADHER MOHAMMED', 'M', NULL, 'Iraq');
INSERT INTO Athletes VALUES('1535852', 'MAEDER Maximilian', 'M', NULL, 'Singapore');
INSERT INTO Athletes VALUES('1535853', 'LO Ryan', 'M', NULL, 'Singapore');
INSERT INTO Athletes VALUES('1535854', 'SIM En Yi Letitia', 'F', NULL, 'Singapore');
INSERT INTO Athletes VALUES('1535856', 'TAN Jonathan Eu Jin', 'M', NULL, 'Singapore');
INSERT INTO Athletes VALUES('1535858', 'PEREIRA Veronica Shanti', 'F', NULL, 'Singapore');
INSERT INTO Athletes VALUES('1535910', 'ZAID TAHSEEN', 'M', NULL, 'Iraq');
INSERT INTO Athletes VALUES('1535913', 'HUSSEIN AMER', 'M', NULL, 'Iraq');
INSERT INTO Athletes VALUES('1535914', 'ANAK LISES Bertrand Rhodict', 'M', NULL, 'Malaysia');
INSERT INTO Athletes VALUES('1535916', 'HUSSEIN LAWEND', 'M', NULL, 'Iraq');
INSERT INTO Athletes VALUES('1535918', 'WONG Guanjie Johnathan', 'M', NULL, 'Malaysia');
INSERT INTO Athletes VALUES('1535925', 'MOHAMAD ZUBIR Nur Aisyah', 'F', NULL, 'Malaysia');
INSERT INTO Athletes VALUES('1535926', 'MOHAMAD LATIF Nur Shazrin', 'F', NULL, 'Malaysia');
INSERT INTO Athletes VALUES('1535927', 'ALI JASIM', 'M', NULL, 'Iraq');
INSERT INTO Athletes VALUES('1535928', 'KARRAR SAAD', 'M', NULL, 'Iraq');
INSERT INTO Athletes VALUES('1535929', 'KARRAR MOHAMMED', 'M', NULL, 'Iraq');
INSERT INTO Athletes VALUES('1535930', 'NIHAD MOHAMMED', 'M', NULL, 'Iraq');
INSERT INTO Athletes VALUES('1535959', 'DOUA Camil', 'M', NULL, 'Mauritania');
INSERT INTO Athletes VALUES('1535993', 'CHEW Caroline', 'F', NULL, 'Singapore');
INSERT INTO Athletes VALUES('1536032', 'HERNANDEZ FLORES Margarita', 'F', NULL, 'Mexico');
INSERT INTO Athletes VALUES('1536045', 'SALIMI Arian', 'M', NULL, 'IR Iran');
INSERT INTO Athletes VALUES('1536058', 'BARKHORDARI Mehran', 'M', NULL, 'IR Iran');
INSERT INTO Athletes VALUES('1536064', 'NEMATZADEH Mobina', 'F', NULL, 'IR Iran');
INSERT INTO Athletes VALUES('1536067', 'KIYANICHANDEH Nahid', 'F', NULL, 'IR Iran');
INSERT INTO Athletes VALUES('1536157', 'MPALI Adam', 'M', NULL, 'Gabon');
INSERT INTO Athletes VALUES('1536175', 'AMISON Naima-Zahra', 'F', NULL, 'Djibouti');
INSERT INTO Athletes VALUES('1536184', 'STREHLKE DELGADO Paulo', 'M', NULL, 'Mexico');
INSERT INTO Athletes VALUES('1536190', 'SANDOVAL AYALA Martha', 'F', NULL, 'Mexico');
INSERT INTO Athletes VALUES('1536196', 'ESTUDILLO TORRES Alejandra', 'F', NULL, 'Mexico');
INSERT INTO Athletes VALUES('1536197', 'CELAYA HERNANDEZ Juan Manuel', 'M', NULL, 'Mexico');
INSERT INTO Athletes VALUES('1536198', 'VAZQUEZ MONTANO Aranza', 'F', NULL, 'Mexico');
INSERT INTO Athletes VALUES('1536207', 'ALIPOUR SHENAZANDIFARD Reza', 'M', NULL, 'IR Iran');
INSERT INTO Athletes VALUES('1536214', 'ALAMIAN Nima', 'M', NULL, 'IR Iran');
INSERT INTO Athletes VALUES('1536215', 'ALAMIYAN Noshad', 'M', NULL, 'IR Iran');
INSERT INTO Athletes VALUES('1536233', 'YASEEN Taha Hussein', 'M', NULL, 'Iraq');
INSERT INTO Athletes VALUES('1536251', 'MAAN Tulika', 'F', NULL, 'India');
INSERT INTO Athletes VALUES('1536341', 'ANCER Abraham', 'M', NULL, 'Mexico');
INSERT INTO Athletes VALUES('1536368', 'SHARMA Shubhankar', 'M', NULL, 'India');
INSERT INTO Athletes VALUES('1536371', 'BHULLAR Gaganjeet', 'M', NULL, 'India');
INSERT INTO Athletes VALUES('1536372', 'GIRMA Ermias', 'M', NULL, 'Ethiopia');
INSERT INTO Athletes VALUES('1536460', 'ROJAS Carlos', 'M', NULL, 'Mexico');
INSERT INTO Athletes VALUES('1536467', 'MARTINEZ WING Bruno', 'M', NULL, 'Mexico');
INSERT INTO Athletes VALUES('1536479', 'VAZQUEZ Ana', 'F', NULL, 'Mexico');
INSERT INTO Athletes VALUES('1536494', 'RIVERA Edgar', 'M', NULL, 'Mexico');
INSERT INTO Athletes VALUES('1536495', 'TAMAYO-GARZA Cecilia', 'F', NULL, 'Mexico');
INSERT INTO Athletes VALUES('1536496', 'ALEMU Habitam', 'F', NULL, 'Ethiopia');
INSERT INTO Athletes VALUES('1536497', 'MESELE Worknesh', 'F', NULL, 'Ethiopia');
INSERT INTO Athletes VALUES('1536498', 'DUGUMA Tsige', 'F', NULL, 'Ethiopia');
INSERT INTO Athletes VALUES('1536522', 'ASHOK Aditi', 'F', NULL, 'India');
INSERT INTO Athletes VALUES('1536523', 'DAGAR Diksha', 'F', NULL, 'India');
INSERT INTO Athletes VALUES('1536568', 'FAYISA Abdisa', 'M', NULL, 'Ethiopia');
INSERT INTO Athletes VALUES('1536585', 'GUERRERO Ilse', 'F', NULL, 'Mexico');
INSERT INTO Athletes VALUES('1536599', 'CHAMA Noel', 'M', NULL, 'Mexico');
INSERT INTO Athletes VALUES('1536600', 'ORTIZ Ricardo', 'M', NULL, 'Mexico');
INSERT INTO Athletes VALUES('1536624', 'SHAHSAVARI Neda', 'F', NULL, 'IR Iran');
INSERT INTO Athletes VALUES('1536632', 'FALLAH Mobina', 'F', NULL, 'IR Iran');
INSERT INTO Athletes VALUES('1536648', 'LOH Kean Yew', 'M', NULL, 'Singapore');
INSERT INTO Athletes VALUES('1536649', 'HEE Yong Kai Terry', 'M', NULL, 'Singapore');
INSERT INTO Athletes VALUES('1536650', 'TAN Wei Han Jessica', 'F', NULL, 'Singapore');
INSERT INTO Athletes VALUES('1536651', 'YEO Jia Min', 'F', NULL, 'Singapore');
INSERT INTO Athletes VALUES('1536669', 'LABIB Ali', 'M', NULL, 'IR Iran');
INSERT INTO Athletes VALUES('1536683', 'FASIHI Farzaneh', 'F', NULL, 'IR Iran');
INSERT INTO Athletes VALUES('1536701', 'TAFTIAN Hassan', 'M', NULL, 'IR Iran');
INSERT INTO Athletes VALUES('1536721', 'PANWAR Balraj', 'M', NULL, 'India');
INSERT INTO Athletes VALUES('1536885', 'RICKETTS Shanieka', 'F', NULL, 'Jamaica');
INSERT INTO Athletes VALUES('1536925', 'HARRIS Naquille', 'M', NULL, 'St Kitts and Nevis');
INSERT INTO Athletes VALUES('1536961', 'DAVOUDI Ali', 'M', NULL, 'IR Iran');
INSERT INTO Athletes VALUES('1536971', 'JAVADI ALIABADI Mir Mostafa', 'M', NULL, 'IR Iran');
INSERT INTO Athletes VALUES('1536983', 'WELTEJI Diribe', 'F', NULL, 'Ethiopia');
INSERT INTO Athletes VALUES('1536990', 'HAYLOM Birke', 'F', NULL, 'Ethiopia');
INSERT INTO Athletes VALUES('1536992', 'HAILU Freweyni', 'F', NULL, 'Ethiopia');
INSERT INTO Athletes VALUES('1536996', 'AGHAMIRZAEIJENAGHARD Ali', 'M', NULL, 'IR Iran');
INSERT INTO Athletes VALUES('1536997', 'MAYALA Freddy', 'M', NULL, 'Congo');
INSERT INTO Athletes VALUES('1536998', 'AREGAWI Berihu', 'M', NULL, 'Ethiopia');
INSERT INTO Athletes VALUES('1536999', 'KEJELCHA Yomif', 'M', NULL, 'Ethiopia');
INSERT INTO Athletes VALUES('1537001', 'GEBRHIWET Hagos', 'M', NULL, 'Ethiopia');
INSERT INTO Athletes VALUES('1537002', 'BOBIMBO Vanessa', 'F', NULL, 'Congo');
INSERT INTO Athletes VALUES('1537010', 'NGOYE Natacha', 'F', NULL, 'Congo');
INSERT INTO Athletes VALUES('1537012', 'SAIKHOM Mirabai Chanu', 'F', NULL, 'India');
INSERT INTO Athletes VALUES('1537049', 'BAREGA Selemon', 'M', NULL, 'Ethiopia');
INSERT INTO Athletes VALUES('1537052', 'TEFERA Samuel', 'M', NULL, 'Ethiopia');
INSERT INTO Athletes VALUES('1537053', 'YIHUNE Addisu', 'M', NULL, 'Ethiopia');
INSERT INTO Athletes VALUES('1537057', 'MEHARY Biniam', 'M', NULL, 'Ethiopia');
INSERT INTO Athletes VALUES('1537066', 'TAYE Ejgayehu', 'F', NULL, 'Ethiopia');
INSERT INTO Athletes VALUES('1537069', 'EISA Medina', 'F', NULL, 'Ethiopia');
INSERT INTO Athletes VALUES('1537079', 'GEBRESELAMA Tsigie', 'F', NULL, 'Ethiopia');
INSERT INTO Athletes VALUES('1537135', 'ZENG Jian', 'F', NULL, 'Singapore');
INSERT INTO Athletes VALUES('1537137', 'QUEK Izaac', 'M', NULL, 'Singapore');
INSERT INTO Athletes VALUES('1537144', 'VEGA Jerome', 'M', NULL, 'Puerto Rico');
INSERT INTO Athletes VALUES('1537145', 'OWENS-DELERME Ayden', 'M', NULL, 'Puerto Rico');
INSERT INTO Athletes VALUES('1537149', 'de ORBETA Rachelle', 'F', NULL, 'Puerto Rico');
INSERT INTO Athletes VALUES('1537150', 'SCOTT Gabby', 'F', NULL, 'Puerto Rico');
INSERT INTO Athletes VALUES('1537163', 'D''AMOUR Nicholas', 'M', NULL, '"Virgin Islands');
INSERT INTO Athletes VALUES('1537168', 'CASTRO RIVERA Luis', 'M', NULL, 'Puerto Rico');
INSERT INTO Athletes VALUES('1537180', 'CEBALLOS Macarena', 'F', NULL, 'Argentina');
INSERT INTO Athletes VALUES('1537183', 'CAMACHO-QUINN Jasmine', 'F', NULL, 'Puerto Rico');
INSERT INTO Athletes VALUES('1537185', 'CHEVRIER Luc', 'M', NULL, 'Saint Lucia');
INSERT INTO Athletes VALUES('1537187', 'FERNANDEZ GAMBOA Pedro Luis', 'M', NULL, 'Puerto Rico');
INSERT INTO Athletes VALUES('1537188', 'RIVERA Sebastian C', 'M', NULL, 'Puerto Rico');
INSERT INTO Athletes VALUES('1537189', 'LOZADA MOTTA Ashleyann', 'F', NULL, 'Puerto Rico');
INSERT INTO Athletes VALUES('1537191', 'PULIDO ORTIZ Celia', 'F', NULL, 'Mexico');
INSERT INTO Athletes VALUES('1537203', 'HYDE Jaheel', 'M', NULL, 'Jamaica');
INSERT INTO Athletes VALUES('1537204', 'IGA Jorge', 'M', NULL, 'Mexico');
INSERT INTO Athletes VALUES('1537209', 'HEIN Agostina', 'F', NULL, 'Argentina');
INSERT INTO Athletes VALUES('1537256', 'SASSER Mathlynn', 'F', NULL, 'Marshall Islands');
INSERT INTO Athletes VALUES('1537272', 'HEPLER Kayla', 'F', NULL, 'Marshall Islands');
INSERT INTO Athletes VALUES('1537273', 'KINONO Philli', 'M', NULL, 'Marshall Islands');
INSERT INTO Athletes VALUES('1537276', 'GARRIDO Luis Ramon', 'M', NULL, 'Mexico');
INSERT INTO Athletes VALUES('1537286', 'MARTINEZ Paulina', 'F', NULL, 'Mexico');
INSERT INTO Athletes VALUES('1537287', 'AWITI ALCARAZ Prisca', 'F', NULL, 'Mexico');
INSERT INTO Athletes VALUES('1537312', 'REZAEI Mohammad Nabi', 'M', NULL, 'IR Iran');
INSERT INTO Athletes VALUES('1537323', 'MUSTAFA SAADOON', 'M', NULL, 'Iraq');
INSERT INTO Athletes VALUES('1537325', 'ALFRED Julien', 'F', NULL, 'Saint Lucia');
INSERT INTO Athletes VALUES('1537331', 'JOSEPH Michael', 'M', NULL, 'Saint Lucia');
INSERT INTO Athletes VALUES('1537336', 'YOUSSEF AMYN', 'M', NULL, 'Iraq');
INSERT INTO Athletes VALUES('1537345', 'TSEGAY Gudaf', 'F', NULL, 'Ethiopia');
INSERT INTO Athletes VALUES('1537349', 'ALSADEQ Julyana', 'F', NULL, 'Jordan');
INSERT INTO Athletes VALUES('1537368', 'TESFAY Fotyen', 'F', NULL, 'Ethiopia');
INSERT INTO Athletes VALUES('1537375', 'MOJALLALTOPRAGHGHALE Fatemeh', 'F', NULL, 'IR Iran');
INSERT INTO Athletes VALUES('1537376', 'ELSHARABATY Saleh', 'M', NULL, 'Jordan');
INSERT INTO Athletes VALUES('1537377', 'AL KHATRI Said', 'M', NULL, 'Oman');
INSERT INTO Athletes VALUES('1537394', 'AL ADAWI Issa Samir Hamed', 'M', NULL, 'Oman');
INSERT INTO Athletes VALUES('1537401', 'KAREEM Zaid', 'M', NULL, 'Jordan');
INSERT INTO Athletes VALUES('1537402', 'SARAVANAN Vishnu', 'M', NULL, 'India');
INSERT INTO Athletes VALUES('1537405', 'KUMANAN Nethra', 'F', NULL, 'India');
INSERT INTO Athletes VALUES('1537465', 'SARAVIA Ulises', 'M', NULL, 'Argentina');
INSERT INTO Athletes VALUES('1537510', 'BORELLI Florencia', 'F', NULL, 'Argentina');
INSERT INTO Athletes VALUES('1537518', 'CASETTA Belen', 'F', NULL, 'Argentina');
INSERT INTO Athletes VALUES('1537531', 'GOMEZ Joaquin', 'M', NULL, 'Argentina');
INSERT INTO Athletes VALUES('1537538', 'LARREGINA Elian', 'M', NULL, 'Argentina');
INSERT INTO Athletes VALUES('1537547', 'SASIA Nazareno', 'M', NULL, 'Argentina');
INSERT INTO Athletes VALUES('1537549', 'GADAYI Edwin Kwabla', 'M', NULL, 'Ghana');
INSERT INTO Athletes VALUES('1537579', 'ODLUM-SMITH Jayhan Jamaud', 'M', NULL, 'Saint Lucia');
INSERT INTO Athletes VALUES('1537661', 'ABUZRIBA Ahmed', 'M', NULL, 'Libya');
INSERT INTO Athletes VALUES('1537667', 'BUKRAH Mohamed', 'M', NULL, 'Libya');
INSERT INTO Athletes VALUES('1537686', 'BOUDINA Sid Ali', 'M', NULL, 'Algeria');
INSERT INTO Athletes VALUES('1537927', 'GIL Federico', 'M', NULL, 'Argentina');
INSERT INTO Athletes VALUES('1537929', 'GUTIERREZ Marcelo Julian', 'M', NULL, 'Argentina');
INSERT INTO Athletes VALUES('1537932', 'RUSSO Fernanda', 'F', NULL, 'Argentina');
INSERT INTO Athletes VALUES('1538007', 'CROOKS Jordan', 'M', NULL, 'Cayman Islands');
INSERT INTO Athletes VALUES('1538028', 'BOSCO Eugenia', 'F', NULL, 'Argentina');
INSERT INTO Athletes VALUES('1538040', 'FERRETTI Chiara', 'F', NULL, 'Argentina');
INSERT INTO Athletes VALUES('1538041', 'MAJDALANI Mateo', 'M', NULL, 'Argentina');
INSERT INTO Athletes VALUES('1538044', 'CRUZ SAUBIDET BIRKNER Francisco', 'M', NULL, 'Argentina');
INSERT INTO Athletes VALUES('1538048', 'TURIENZO Maria Catalina', 'F', NULL, 'Argentina');
INSERT INTO Athletes VALUES('1538059', 'EDGHILL Chelsea', 'F', NULL, 'Guyana');
INSERT INTO Athletes VALUES('1538078', 'TONDAIMAN Prithviraj', 'M', NULL, 'India');
INSERT INTO Athletes VALUES('1538084', 'KUSALE Swapnil', 'M', NULL, 'India');
INSERT INTO Athletes VALUES('1538096', 'BATRA Manika', 'F', NULL, 'India');
INSERT INTO Athletes VALUES('1538104', 'THAKKAR Manav Vikash', 'M', NULL, 'India');
INSERT INTO Athletes VALUES('1538124', 'ZMUSHKA Alina', 'F', NULL, 'AIN');
INSERT INTO Athletes VALUES('1538136', 'AKULA Sreeja', 'F', NULL, 'India');
INSERT INTO Athletes VALUES('1538146', 'CHAUHAN Maheshwari', 'F', NULL, 'India');
INSERT INTO Athletes VALUES('1538150', 'SHYMANOVICH Ilya', 'M', NULL, 'AIN');
INSERT INTO Athletes VALUES('1538151', 'ACHANTA Sharath Kamal', 'M', NULL, 'India');
INSERT INTO Athletes VALUES('1538153', 'SHKURDAI Anastasiya', 'F', NULL, 'AIN');
INSERT INTO Athletes VALUES('1538154', 'MOUDGIL Anjum', 'F', NULL, 'India');
INSERT INTO Athletes VALUES('1538157', 'SINGH Shreyasi', 'F', NULL, 'India');
INSERT INTO Athletes VALUES('1538159', 'BHAKER Manu', 'F', NULL, 'India');
INSERT INTO Athletes VALUES('1538160', 'ZALATY Yauheni', 'M', NULL, 'AIN');
INSERT INTO Athletes VALUES('1538161', 'VALARIVAN Elavenil', 'F', NULL, 'India');
INSERT INTO Athletes VALUES('1538190', 'DESAI Harmeet', 'M', NULL, 'India');
INSERT INTO Athletes VALUES('1538193', 'KAMATH Archana Girish', 'F', NULL, 'India');
INSERT INTO Athletes VALUES('1538234', 'GREENE Kennice Aphenie', 'F', NULL, 'StVincent&Grenadines');
INSERT INTO Athletes VALUES('1538243', 'JOACHIM Alex', 'M', NULL, 'StVincent&Grenadines');
INSERT INTO Athletes VALUES('1538244', 'ALBERTARRIO Agustina', 'F', NULL, 'Argentina');
INSERT INTO Athletes VALUES('1538253', 'ALONSO Agostina', 'F', NULL, 'Argentina');
INSERT INTO Athletes VALUES('1538260', 'CAMPOY Maria', 'F', NULL, 'Argentina');
INSERT INTO Athletes VALUES('1538261', 'CAIRO Sofia', 'F', NULL, 'Argentina');
INSERT INTO Athletes VALUES('1538262', 'CASAS Lara', 'F', NULL, 'Argentina');
INSERT INTO Athletes VALUES('1538263', 'CASTELLARO MORELLO Juana', 'F', NULL, 'Argentina');
INSERT INTO Athletes VALUES('1538266', 'COSENTINO Cristina', 'F', NULL, 'Argentina');
INSERT INTO Athletes VALUES('1538274', 'GORZELANY Agustina', 'F', NULL, 'Argentina');
INSERT INTO Athletes VALUES('1538276', 'GRANATTO Maria', 'F', NULL, 'Argentina');
INSERT INTO Athletes VALUES('1538277', 'JANKUNAS Julieta', 'F', NULL, 'Argentina');
INSERT INTO Athletes VALUES('1538294', 'RAPOSO RUIZ de los LLANOS Valentina', 'F', NULL, 'Argentina');
INSERT INTO Athletes VALUES('1538295', 'SANCHEZ MOCCIA Rocio', 'F', NULL, 'Argentina');
INSERT INTO Athletes VALUES('1538299', 'SAUZE VALDEZ Victoria', 'F', NULL, 'Argentina');
INSERT INTO Athletes VALUES('1538304', 'TOCCALINO Sofia', 'F', NULL, 'Argentina');
INSERT INTO Athletes VALUES('1538305', 'TRINCHINETTI Eugenia', 'F', NULL, 'Argentina');
INSERT INTO Athletes VALUES('1538363', 'BUGALLO Agustin', 'M', NULL, 'Argentina');
INSERT INTO Athletes VALUES('1538365', 'CAPURRO ZUBELDIA Bautista', 'M', NULL, 'Argentina');
INSERT INTO Athletes VALUES('1538366', 'CASELLA SCHUTH Maico', 'M', NULL, 'Argentina');
INSERT INTO Athletes VALUES('1538367', 'CATAN Juan', 'M', NULL, 'Argentina');
INSERT INTO Athletes VALUES('1538370', 'DOMENE Tomas', 'M', NULL, 'Argentina');
INSERT INTO Athletes VALUES('1538372', 'HABIF Thomas', 'M', NULL, 'Argentina');
INSERT INTO Athletes VALUES('1538375', 'KEENAN Nicolas', 'M', NULL, 'Argentina');
INSERT INTO Athletes VALUES('1538378', 'MARCUCCI Tadeo', 'M', NULL, 'Argentina');
INSERT INTO Athletes VALUES('1538379', 'MARTINEZ Lucas', 'M', NULL, 'Argentina');
INSERT INTO Athletes VALUES('1538380', 'MARTINS Tobias', 'M', NULL, 'Argentina');
INSERT INTO Athletes VALUES('1538386', 'JAVER Mahsa', 'F', NULL, 'IR Iran');
INSERT INTO Athletes VALUES('1538396', 'NOROUZI TAZEH KAND Zeinab', 'F', NULL, 'IR Iran');
INSERT INTO Athletes VALUES('1538415', 'BEYRANVAND Mohammad', 'M', NULL, 'IR Iran');
INSERT INTO Athletes VALUES('1538421', 'ROSTAMIYAN Haniyeh', 'F', NULL, 'IR Iran');
INSERT INTO Athletes VALUES('1538436', 'AMINI POZVEH Fatemeh', 'F', NULL, 'IR Iran');
INSERT INTO Athletes VALUES('1538442', 'CHEHEL AMIRANI Shermineh', 'F', NULL, 'IR Iran');
INSERT INTO Athletes VALUES('1538449', 'AMAISTROAIE Madalina', 'F', NULL, 'Romania');
INSERT INTO Athletes VALUES('1538482', 'BOUZIDI Carole Diana', 'F', NULL, 'Algeria');
INSERT INTO Athletes VALUES('1538488', 'GERBEKOV Askerbii', 'M', NULL, 'Bahrain');
INSERT INTO Athletes VALUES('1538504', 'CISSE Arthur', 'M', NULL, 'Côte d''Ivoire');
INSERT INTO Athletes VALUES('1538505', 'KONE Maboundou', 'F', NULL, 'Côte d''Ivoire');
INSERT INTO Athletes VALUES('1538622', 'NURMATOV Shakhzod', 'M', NULL, 'Uzbekistan');
INSERT INTO Athletes VALUES('1538627', 'PRAKATEN Anna', 'F', NULL, 'Uzbekistan');
INSERT INTO Athletes VALUES('1538632', 'SAFAROLIYEV Sobirjon', 'M', NULL, 'Uzbekistan');
INSERT INTO Athletes VALUES('1538648', 'OLFATI Mahdi', 'M', NULL, 'IR Iran');
INSERT INTO Athletes VALUES('1538662', 'CHEN Jiexian Stephenie', 'F', NULL, 'Singapore');
INSERT INTO Athletes VALUES('1538729', 'MAZZILLI Agustin', 'M', NULL, 'Argentina');
INSERT INTO Athletes VALUES('1538734', 'MONJA Federico', 'M', NULL, 'Argentina');
INSERT INTO Athletes VALUES('1538737', 'REY Matias', 'M', NULL, 'Argentina');
INSERT INTO Athletes VALUES('1538740', 'SANTIAGO Tomas', 'M', NULL, 'Argentina');
INSERT INTO Athletes VALUES('1538741', 'TARAZONA Santiago', 'M', NULL, 'Argentina');
INSERT INTO Athletes VALUES('1538742', 'TOSCANI Lucas', 'M', NULL, 'Argentina');
INSERT INTO Athletes VALUES('1538800', 'VERNICE Agustin', 'M', NULL, 'Argentina');
INSERT INTO Athletes VALUES('1538830', 'BROWN Janeek', 'F', NULL, 'Jamaica');
INSERT INTO Athletes VALUES('1538875', 'MOLINA Gonzalo Nahuel', 'M', NULL, 'Argentina');
INSERT INTO Athletes VALUES('1538878', 'VILLEGAS Federico Emiliano', 'M', NULL, 'Argentina');
INSERT INTO Athletes VALUES('1538893', 'CAMERON Lloydricia', 'F', NULL, 'Jamaica');
INSERT INTO Athletes VALUES('1538903', 'PERINCHIEF Jah-Nhai', 'M', NULL, 'Bermuda');
INSERT INTO Athletes VALUES('1538904', 'CLAYTON Rushell', 'F', NULL, 'Jamaica');
INSERT INTO Athletes VALUES('1538910', 'DUFFY Flora', 'F', NULL, 'Bermuda');
INSERT INTO Athletes VALUES('1538934', 'FIRFIRICA Alin Alexandru', 'M', NULL, 'Romania');
INSERT INTO Athletes VALUES('1538935', 'GHELBER Bianca Florentina', 'F', NULL, 'Romania');
INSERT INTO Athletes VALUES('1538937', 'ION Diana Ana Maria', 'F', NULL, 'Romania');
INSERT INTO Athletes VALUES('1538939', 'MELLY Joan Chelimo', 'F', NULL, 'Romania');
INSERT INTO Athletes VALUES('1538999', 'MERINGOR Delvine Relin', 'F', NULL, 'Romania');
INSERT INTO Athletes VALUES('1539000', 'MIKLOS Andrea', 'F', NULL, 'Romania');
INSERT INTO Athletes VALUES('1539008', 'NOVAC Alexandru Mihaita', 'M', NULL, 'Romania');
INSERT INTO Athletes VALUES('1539114', 'PRANNOY H. S', 'M', NULL, 'India');
INSERT INTO Athletes VALUES('1539123', 'RANKIREDDY Satwiksairaj', 'M', NULL, 'India');
INSERT INTO Athletes VALUES('1539125', 'SHETTY Chirag', 'M', NULL, 'India');
INSERT INTO Athletes VALUES('1539131', 'BERTEMES Bob', 'M', NULL, 'Luxembourg');
INSERT INTO Athletes VALUES('1539157', 'PUSARLA V. Sindhu', 'F', NULL, 'India');
INSERT INTO Athletes VALUES('1539180', 'AGARWALLA Anush', 'M', NULL, 'India');
INSERT INTO Athletes VALUES('1539183', 'CRASTO Tanisha', 'F', NULL, 'India');
INSERT INTO Athletes VALUES('1539188', 'PONNAPPA Ashwini', 'F', NULL, 'India');
INSERT INTO Athletes VALUES('1539303', 'ROTARU-KOTTMANN Alina', 'F', NULL, 'Romania');
INSERT INTO Athletes VALUES('1539314', 'RUTTO Stella', 'F', NULL, 'Romania');
INSERT INTO Athletes VALUES('1539328', 'STANCIU Daniela', 'F', NULL, 'Romania');
INSERT INTO Athletes VALUES('1539340', 'TALOS Elena Andreea', 'F', NULL, 'Romania');
INSERT INTO Athletes VALUES('1539342', 'TOADER Andrei Rares', 'M', NULL, 'Romania');
INSERT INTO Athletes VALUES('1539412', 'GOMES Filipe', 'M', NULL, 'Malawi');
INSERT INTO Athletes VALUES('1539497', 'OCAMPO Daiana', 'F', NULL, 'Argentina');
INSERT INTO Athletes VALUES('1539505', 'ARCHIBALD Emanuel', 'M', NULL, 'Guyana');
INSERT INTO Athletes VALUES('1539510', 'ABRAMS Aliyah', 'F', NULL, 'Guyana');
INSERT INTO Athletes VALUES('1539530', 'NOEL Raekwon Jibril', 'M', NULL, 'Guyana');
INSERT INTO Athletes VALUES('1539532', 'PERSAUD Aleka Kylela', 'F', NULL, 'Guyana');
INSERT INTO Athletes VALUES('1539540', 'ALLERS-LIBURD Zahria', 'F', NULL, 'St Kitts and Nevis');
INSERT INTO Athletes VALUES('1539547', 'TRAORE Cheickna', 'M', NULL, 'Côte d''Ivoire');
INSERT INTO Athletes VALUES('1539548', 'TIE Whitney', 'F', NULL, 'Côte d''Ivoire');
INSERT INTO Athletes VALUES('1539607', 'SIDHU Vijayveer', 'M', NULL, 'India');
INSERT INTO Athletes VALUES('1539611', 'TOMAR Aishwary Pratap Singh', 'M', NULL, 'India');
INSERT INTO Athletes VALUES('1539615', 'NARUKA Anant Jeet Singh', 'M', NULL, 'India');
INSERT INTO Athletes VALUES('1539628', 'ANISH Anish', 'M', NULL, 'India');
INSERT INTO Athletes VALUES('1539636', 'BABUTA Arjun', 'M', NULL, 'India');
INSERT INTO Athletes VALUES('1539643', 'CHEEMA Arjun Singh', 'M', NULL, 'India');
INSERT INTO Athletes VALUES('1539683', 'BOUSHITA Abderrahmane', 'M', NULL, 'Morocco');
INSERT INTO Athletes VALUES('1539720', 'SINGH Sandee', 'M', NULL, 'India');
INSERT INTO Athletes VALUES('1539747', 'SAMRA Sift Kaur', 'F', NULL, 'India');
INSERT INTO Athletes VALUES('1539752', 'SINGH Esha', 'F', NULL, 'India');
INSERT INTO Athletes VALUES('1539754', 'RAMITA Ramita', 'F', NULL, 'India');
INSERT INTO Athletes VALUES('1539757', 'KUMARI Rajeshwari', 'F', NULL, 'India');
INSERT INTO Athletes VALUES('1539767', 'SANGWAN Rhythm', 'F', NULL, 'India');
INSERT INTO Athletes VALUES('1539849', 'SEN Lakshya', 'M', NULL, 'India');
INSERT INTO Athletes VALUES('1539886', 'di TELLA Pascual Maria', 'M', NULL, 'Argentina');
INSERT INTO Athletes VALUES('1539948', 'DARRAGH Rachael', 'F', NULL, 'Ireland');
INSERT INTO Athletes VALUES('1539950', 'McNULTY Harry', 'M', NULL, 'Ireland');
INSERT INTO Athletes VALUES('1539951', 'MOLLEN Bryan', 'M', NULL, 'Ireland');
INSERT INTO Athletes VALUES('1539952', 'KENNEDY Terry', 'M', NULL, 'Ireland');
INSERT INTO Athletes VALUES('1539954', 'WALSH Grainne', 'F', NULL, 'Ireland');
INSERT INTO Athletes VALUES('1539959', 'PASSMORE Jake', 'M', NULL, 'Ireland');
INSERT INTO Athletes VALUES('1539961', 'HEALY Sarah', 'F', NULL, 'Ireland');
INSERT INTO Athletes VALUES('1539962', 'McCANN Luke', 'M', NULL, 'Ireland');
INSERT INTO Athletes VALUES('1539963', 'McCORMACK Fionnuala', 'F', NULL, 'Ireland');
INSERT INTO Athletes VALUES('1539966', 'CATTERSON Victoria', 'F', NULL, 'Ireland');
INSERT INTO Athletes VALUES('1539968', 'FERGUSON Conor', 'M', NULL, 'Ireland');
INSERT INTO Athletes VALUES('1539969', 'WIFFEN Daniel', 'M', NULL, 'Ireland');
INSERT INTO Athletes VALUES('1539971', 'ARMITAGE Megan', 'F', NULL, 'Ireland');
INSERT INTO Athletes VALUES('1539974', 'GILLESPIE Lara', 'F', NULL, 'Ireland');
INSERT INTO Athletes VALUES('1539976', 'MURPHY Kelly', 'F', NULL, 'Ireland');
INSERT INTO Athletes VALUES('1539977', 'GRIFFIN Mia', 'F', NULL, 'Ireland');
INSERT INTO Athletes VALUES('1539978', 'CREIGHTON Erin', 'F', NULL, 'Ireland');
INSERT INTO Athletes VALUES('1539982', 'SHARPE Alice', 'F', NULL, 'Ireland');
INSERT INTO Athletes VALUES('1539983', 'HEALY Ben', 'M', NULL, 'Ireland');
INSERT INTO Athletes VALUES('1539985', 'MAGUIRE Leona', 'F', NULL, 'Ireland');
INSERT INTO Athletes VALUES('1539986', 'Mc CLENAGHAN Rhys', 'M', NULL, 'Ireland');
INSERT INTO Athletes VALUES('1539990', 'MURTAGH Fiona', 'F', NULL, 'Ireland');
INSERT INTO Athletes VALUES('1539991', 'MAGNER Imogen', 'F', NULL, 'Ireland');
INSERT INTO Athletes VALUES('1539992', 'LONG Natalie', 'F', NULL, 'Ireland');
INSERT INTO Athletes VALUES('1539993', 'CASEY Aoife', 'F', NULL, 'Ireland');
INSERT INTO Athletes VALUES('1539998', 'KEOGH Aifric', 'F', NULL, 'Ireland');
INSERT INTO Athletes VALUES('1540039', 'TOSTI Alejandro', 'M', NULL, 'Argentina');
INSERT INTO Athletes VALUES('1540108', 'BAR Juan', 'M', NULL, 'Argentina');
INSERT INTO Athletes VALUES('1540112', 'BONANNO Nicolas', 'M', NULL, 'Argentina');
INSERT INTO Athletes VALUES('1540120', 'FERNANDEZ Federico', 'M', NULL, 'Argentina');
INSERT INTO Athletes VALUES('1540143', 'FISCHER Guillermo', 'M', NULL, 'Argentina');
INSERT INTO Athletes VALUES('1540144', 'MACIEL Leonel', 'M', NULL, 'Argentina');
INSERT INTO Athletes VALUES('1540173', 'PENRUDDOCKE Adriana', 'F', NULL, 'Bermuda');
INSERT INTO Athletes VALUES('1540175', 'MARTINEZ CAMI Pedro', 'M', NULL, 'Argentina');
INSERT INTO Athletes VALUES('1540176', 'WEBSTER Charlotte', 'F', NULL, 'Cayman Islands');
INSERT INTO Athletes VALUES('1540177', 'MOSCARIELLO Lucas', 'M', NULL, 'Argentina');
INSERT INTO Athletes VALUES('1540178', 'MOYANO Andres', 'M', NULL, 'Argentina');
INSERT INTO Athletes VALUES('1540179', 'MOURINO Gaston', 'M', NULL, 'Argentina');
INSERT INTO Athletes VALUES('1540180', 'PARKER James', 'M', NULL, 'Argentina');
INSERT INTO Athletes VALUES('1540181', 'PIZARRO Federico', 'M', NULL, 'Argentina');
INSERT INTO Athletes VALUES('1540184', 'CROOKS Jillian Janis Geohagan', 'F', NULL, 'Cayman Islands');
INSERT INTO Athletes VALUES('1540190', 'HARVEY Emma', 'F', NULL, 'Bermuda');
INSERT INTO Athletes VALUES('1540216', 'HAWLEY Erica', 'F', NULL, 'Bermuda');
INSERT INTO Athletes VALUES('1540226', 'SMITH Tyler', 'M', NULL, 'Bermuda');
INSERT INTO Athletes VALUES('1540262', 'ALEXUC CIURARIU Alin', 'M', NULL, 'Romania');
INSERT INTO Athletes VALUES('1540263', 'ARNAUT Razvan', 'M', NULL, 'Romania');
INSERT INTO Athletes VALUES('1540273', 'ANA Andreea Beatrice', 'F', NULL, 'Romania');
INSERT INTO Athletes VALUES('1540275', 'AXENTE Catalina', 'F', NULL, 'Romania');
INSERT INTO Athletes VALUES('1540278', 'INCZE Kriszta Tunde', 'F', NULL, 'Romania');
INSERT INTO Athletes VALUES('1540305', 'TAZHUDINOV Akhmed', 'M', NULL, 'Bahrain');
INSERT INTO Athletes VALUES('1540310', 'ERATI Kaimauri', 'M', NULL, 'Kiribati');
INSERT INTO Athletes VALUES('1540334', 'MINASYAN Gor', 'M', NULL, 'Bahrain');
INSERT INTO Athletes VALUES('1540335', 'MONTANO Lesman', 'M', NULL, 'Bahrain');
INSERT INTO Athletes VALUES('1540349', 'AIT BEKKA Jugurtha', 'M', NULL, 'Algeria');
INSERT INTO Athletes VALUES('1540351', 'KADI Mourad', 'M', NULL, 'Algeria');
INSERT INTO Athletes VALUES('1540352', 'BOUALAM Roumaysa', 'F', NULL, 'Algeria');
INSERT INTO Athletes VALUES('1540353', 'KHELIF Imane', 'F', NULL, 'Algeria');
INSERT INTO Athletes VALUES('1540354', 'KHELIF Dounia', 'F', NULL, 'Algeria');
INSERT INTO Athletes VALUES('1540497', 'PIZARRO Ignacio', 'M', NULL, 'Argentina');
INSERT INTO Athletes VALUES('1540498', 'SIMONET Pablo', 'M', NULL, 'Argentina');
INSERT INTO Athletes VALUES('1540499', 'SIMONET Diego', 'M', NULL, 'Argentina');
INSERT INTO Athletes VALUES('1540516', 'BONO Nicolas', 'M', NULL, 'Argentina');
INSERT INTO Athletes VALUES('1540533', 'MONETA Marcos', 'M', NULL, 'Argentina');
INSERT INTO Athletes VALUES('1540534', 'VERA FELD Santiago', 'M', NULL, 'Argentina');
INSERT INTO Athletes VALUES('1540536', 'OSADCZUK Matias', 'M', NULL, 'Argentina');
INSERT INTO Athletes VALUES('1540537', 'ALVAREZ Santiago', 'M', NULL, 'Argentina');
INSERT INTO Athletes VALUES('1540538', 'SCHULZ German', 'M', NULL, 'Argentina');
INSERT INTO Athletes VALUES('1540539', 'PELLANDINI Joaquin', 'M', NULL, 'Argentina');
INSERT INTO Athletes VALUES('1540543', 'REVOL Gaston', 'M', NULL, 'Argentina');
INSERT INTO Athletes VALUES('1540583', 'OPTI Soren', 'M', NULL, 'Suriname');
INSERT INTO Athletes VALUES('1540603', 'ELIZALDE Tomas', 'M', NULL, 'Argentina');
INSERT INTO Athletes VALUES('1540605', 'WADE Tobias', 'M', NULL, 'Argentina');
INSERT INTO Athletes VALUES('1540621', 'GRAZIANO Matteo', 'M', NULL, 'Argentina');
INSERT INTO Athletes VALUES('1540623', 'GONZALEZ Luciano', 'M', NULL, 'Argentina');
INSERT INTO Athletes VALUES('1540624', 'FRAGA Agustin', 'M', NULL, 'Argentina');
INSERT INTO Athletes VALUES('1540625', 'ISGRO Rodrigo', 'M', NULL, 'Argentina');
INSERT INTO Athletes VALUES('1540647', 'DELL OLIO Matias', 'M', NULL, 'Argentina');
INSERT INTO Athletes VALUES('1540688', 'GOMEZ SANCHEZ Manuela', 'F', NULL, 'Colombia');
INSERT INTO Athletes VALUES('1540691', 'SCHREUDERS Mikel', 'M', NULL, 'Aruba');
INSERT INTO Athletes VALUES('1540692', 'WESTERA Ethan', 'M', NULL, 'Aruba');
INSERT INTO Athletes VALUES('1540693', 'van AANHOLT Just', 'M', NULL, 'Aruba');
INSERT INTO Athletes VALUES('1540694', 'ELHAGE Phili', 'M', NULL, 'Aruba');
INSERT INTO Athletes VALUES('1540695', 'HOWELL Shanayah', 'F', NULL, 'Aruba');
INSERT INTO Athletes VALUES('1540701', 'ARIAS CASTANEDA Yeni Marcela', 'F', NULL, 'Colombia');
INSERT INTO Athletes VALUES('1540702', 'VALENCIA VICTORIA Ingrit Lorena', 'F', NULL, 'Colombia');
INSERT INTO Athletes VALUES('1540704', 'GONZALEZ LANDAZURY Yilmar Leandro', 'M', NULL, 'Colombia');
INSERT INTO Athletes VALUES('1540706', 'RODRIGUEZ John Edison', 'M', NULL, 'Colombia');
INSERT INTO Athletes VALUES('1540710', 'ZUMAYA FLORES Goretti Alejandra', 'F', NULL, 'Mexico');
INSERT INTO Athletes VALUES('1540717', 'GBAI Jessika', 'F', NULL, 'Côte d''Ivoire');
INSERT INTO Athletes VALUES('1540829', 'BORDACHYOVA Ekaterina', 'F', NULL, 'Tajikistan');
INSERT INTO Athletes VALUES('1540832', 'DRAGAN Annaliese', 'F', NULL, 'Romania');
INSERT INTO Athletes VALUES('1540905', 'TEIXEIRA SANTANA Herminia', 'F', NULL, 'Sao Tome & Principe');
INSERT INTO Athletes VALUES('1540991', 'GOLUBIC Marko', 'M', NULL, 'Croatia');
INSERT INTO Athletes VALUES('1540998', 'ALONSO ALDERETE Alejandra', 'F', NULL, 'Paraguay');
INSERT INTO Athletes VALUES('1541062', 'BIAGIOLI Romina', 'F', NULL, 'Argentina');
INSERT INTO Athletes VALUES('1541265', 'BARBELIN Lisa', 'F', NULL, 'France');
INSERT INTO Athletes VALUES('1541266', 'CORDEAU Amelie', 'F', NULL, 'France');
INSERT INTO Athletes VALUES('1541268', 'LOPEZ Caroline', 'F', NULL, 'France');
INSERT INTO Athletes VALUES('1541270', 'ADDIS Baptiste', 'M', NULL, 'France');
INSERT INTO Athletes VALUES('1541272', 'CHIRAULT Thomas', 'M', NULL, 'France');
INSERT INTO Athletes VALUES('1541275', 'VALLADONT Jean-Charles', 'M', NULL, 'France');