INSERT INTO Countries VALUES('United States', 'USA');
INSERT INTO Countries VALUES('China', 'CHN');
INSERT INTO Countries VALUES('Japan', 'JPN');
INSERT INTO Countries VALUES('Australia', 'AUS');
INSERT INTO Countries VALUES('France', 'FRA');
INSERT INTO Countries VALUES('Netherlands', 'NED');
INSERT INTO Countries VALUES('Great Britain', 'GBR');
INSERT INTO Countries VALUES('Korea', 'KOR');
INSERT INTO Countries VALUES('Italy', 'ITA');
INSERT INTO Countries VALUES('Germany', 'GER');
INSERT INTO Countries VALUES('New Zealand', 'NZL');
INSERT INTO Countries VALUES('Canada', 'CAN');
INSERT INTO Countries VALUES('Uzbekistan', 'UZB');
INSERT INTO Countries VALUES('Hungary', 'HUN');
INSERT INTO Countries VALUES('Spain', 'ESP');
INSERT INTO Countries VALUES('Sweden', 'SWE');
INSERT INTO Countries VALUES('Kenya', 'KEN');
INSERT INTO Countries VALUES('Norway', 'NOR');
INSERT INTO Countries VALUES('Ireland', 'IRL');
INSERT INTO Countries VALUES('Brazil', 'BRA');
INSERT INTO Countries VALUES('IR Iran', 'IRI');
INSERT INTO Countries VALUES('Ukraine', 'UKR');
INSERT INTO Countries VALUES('Romania', 'ROU');
INSERT INTO Countries VALUES('Georgia', 'GEO');
INSERT INTO Countries VALUES('Belgium', 'BEL');
INSERT INTO Countries VALUES('Bulgaria', 'BUL');
INSERT INTO Countries VALUES('Serbia', 'SRB');
INSERT INTO Countries VALUES('Czechia', 'CZE');
INSERT INTO Countries VALUES('Denmark', 'DEN');
INSERT INTO Countries VALUES('Azerbaijan', 'AZE');
INSERT INTO Countries VALUES('Croatia', 'CRO');
INSERT INTO Countries VALUES('Cuba', 'CUB');
INSERT INTO Countries VALUES('Bahrain', 'BRN');
INSERT INTO Countries VALUES('Slovenia', 'SLO');
INSERT INTO Countries VALUES('Chinese Taipei', 'TPE');
INSERT INTO Countries VALUES('Austria', 'AUT');
INSERT INTO Countries VALUES('"Hong Kong', 'HKG');
INSERT INTO Countries VALUES('Philippines', 'PHI');
INSERT INTO Countries VALUES('Algeria', 'ALG');
INSERT INTO Countries VALUES('Indonesia', 'INA');
INSERT INTO Countries VALUES('Israel', 'ISR');
INSERT INTO Countries VALUES('Poland', 'POL');
INSERT INTO Countries VALUES('Kazakhstan', 'KAZ');
INSERT INTO Countries VALUES('Jamaica', 'JAM');
INSERT INTO Countries VALUES('South Africa', 'RSA');
INSERT INTO Countries VALUES('Thailand', 'THA');
INSERT INTO Countries VALUES('AIN', 'AIN');
INSERT INTO Countries VALUES('Ethiopia', 'ETH');
INSERT INTO Countries VALUES('Switzerland', 'SUI');
INSERT INTO Countries VALUES('Ecuador', 'ECU');
INSERT INTO Countries VALUES('Portugal', 'POR');
INSERT INTO Countries VALUES('Greece', 'GRE');
INSERT INTO Countries VALUES('Argentina', 'ARG');
INSERT INTO Countries VALUES('Egypt', 'EGY');
INSERT INTO Countries VALUES('Tunisia', 'TUN');
INSERT INTO Countries VALUES('Botswana', 'BOT');
INSERT INTO Countries VALUES('Chile', 'CHI');
INSERT INTO Countries VALUES('Saint Lucia', 'LCA');
INSERT INTO Countries VALUES('Uganda', 'UGA');
INSERT INTO Countries VALUES('Dominican Republic', 'DOM');
INSERT INTO Countries VALUES('Guatemala', 'GUA');
INSERT INTO Countries VALUES('Morocco', 'MAR');
INSERT INTO Countries VALUES('Dominica', 'DMA');
INSERT INTO Countries VALUES('Pakistan', 'PAK');
INSERT INTO Countries VALUES('Türkiye', 'TUR');
INSERT INTO Countries VALUES('Mexico', 'MEX');
INSERT INTO Countries VALUES('Armenia', 'ARM');
INSERT INTO Countries VALUES('Colombia', 'COL');
INSERT INTO Countries VALUES('DPR Korea', 'PRK');
INSERT INTO Countries VALUES('Kyrgyzstan', 'KGZ');
INSERT INTO Countries VALUES('Lithuania', 'LTU');
INSERT INTO Countries VALUES('India', 'IND');
INSERT INTO Countries VALUES('Republic of Moldova', 'MDA');
INSERT INTO Countries VALUES('Kosovo', 'KOS');
INSERT INTO Countries VALUES('Cyprus', 'CYP');
INSERT INTO Countries VALUES('Fiji', 'FIJ');
INSERT INTO Countries VALUES('Jordan', 'JOR');
INSERT INTO Countries VALUES('Mongolia', 'MGL');
INSERT INTO Countries VALUES('Panama', 'PAN');
INSERT INTO Countries VALUES('Tajikistan', 'TJK');
INSERT INTO Countries VALUES('Albania', 'ALB');
INSERT INTO Countries VALUES('Grenada', 'GRN');
INSERT INTO Countries VALUES('Malaysia', 'MAS');
INSERT INTO Countries VALUES('Puerto Rico', 'PUR');
INSERT INTO Countries VALUES('Cabo Verde', 'CPV');
INSERT INTO Countries VALUES('Côte d''Ivoire', 'CIV');
INSERT INTO Countries VALUES('EOR', 'EOR');
INSERT INTO Countries VALUES('Peru', 'PER');
INSERT INTO Countries VALUES('Qatar', 'QAT');
INSERT INTO Countries VALUES('Singapore', 'SGP');
INSERT INTO Countries VALUES('Slovakia', 'SVK');
INSERT INTO Countries VALUES('Zambia', 'ZAM');