INSERT INTO Disciplines VALUES('Archery', 'M', 'Invalides');
INSERT INTO Disciplines VALUES('Archery', 'F', 'Invalides');
INSERT INTO Disciplines VALUES('3x3 Basketball', 'M', 'La Concorde 1');
INSERT INTO Disciplines VALUES('3x3 Basketball', 'F', 'La Concorde 1');
INSERT INTO Disciplines VALUES('Artistic Gymnastics', 'M', 'Bercy Arena');
INSERT INTO Disciplines VALUES('Artistic Gymnastics', 'F', 'Bercy Arena');
INSERT INTO Disciplines VALUES('Artistic Swimming', 'F', 'Aquatics Centre');
INSERT INTO Disciplines VALUES('Artistic Swimming', 'M', 'Aquatics Centre');
INSERT INTO Disciplines VALUES('Athletics', 'M', 'Stade de France');
INSERT INTO Disciplines VALUES('Athletics', 'F', 'Stade de France');
INSERT INTO Disciplines VALUES('Badminton', 'M', 'La Chapelle Arena');
INSERT INTO Disciplines VALUES('Badminton', 'F', 'La Chapelle Arena');
INSERT INTO Disciplines VALUES('Basketball', 'M', 'Pierre Mauroy Stadium');
INSERT INTO Disciplines VALUES('Basketball', 'F', 'Pierre Mauroy Stadium');
INSERT INTO Disciplines VALUES('Beach Volleyball', 'M', 'Eiffel Tower Stadium');
INSERT INTO Disciplines VALUES('Beach Volleyball', 'F', 'Eiffel Tower Stadium');
INSERT INTO Disciplines VALUES('Boxing', 'M', 'North Paris Arena');
INSERT INTO Disciplines VALUES('Boxing', 'F', 'North Paris Arena');
INSERT INTO Disciplines VALUES('Breaking', 'M', 'La Concorde 1');
INSERT INTO Disciplines VALUES('Breaking', 'F', 'La Concorde 1');
INSERT INTO Disciplines VALUES('Canoe Slalom', 'F', 'Nautical St - White water');
INSERT INTO Disciplines VALUES('Canoe Slalom', 'M', 'Nautical St - White water');
INSERT INTO Disciplines VALUES('Canoe Sprint', 'M', 'Nautical St - Flat water');
INSERT INTO Disciplines VALUES('Canoe Sprint', 'F', 'Nautical St - Flat water');
INSERT INTO Disciplines VALUES('Cycling BMX Freestyle', 'M', 'La Concorde 2');
INSERT INTO Disciplines VALUES('Cycling BMX Freestyle', 'F', 'La Concorde 2');
INSERT INTO Disciplines VALUES('Cycling BMX Racing', 'M', 'BMX Stadium');
INSERT INTO Disciplines VALUES('Cycling BMX Racing', 'F', 'BMX Stadium');
INSERT INTO Disciplines VALUES('Cycling Mountain Bike', 'M', 'Elancourt Hill');
INSERT INTO Disciplines VALUES('Cycling Mountain Bike', 'F', 'Elancourt Hill');
INSERT INTO Disciplines VALUES('Cycling Road', 'M', 'Pont Alexandre III');
INSERT INTO Disciplines VALUES('Cycling Road', 'F', 'Pont Alexandre III');
INSERT INTO Disciplines VALUES('Cycling Track', 'M', 'National Velodrome');
INSERT INTO Disciplines VALUES('Cycling Track', 'F', 'National Velodrome');
INSERT INTO Disciplines VALUES('Diving', 'M', 'Aquatics Centre');
INSERT INTO Disciplines VALUES('Diving', 'F', 'Aquatics Centre');
INSERT INTO Disciplines VALUES('Equestrian', 'F', 'Château de Versailles');
INSERT INTO Disciplines VALUES('Equestrian', 'M', 'Château de Versailles');
INSERT INTO Disciplines VALUES('Fencing', 'F', 'Grand Palais');
INSERT INTO Disciplines VALUES('Fencing', 'M', 'Grand Palais');
INSERT INTO Disciplines VALUES('Football', 'F', 'Parc des Princes');
INSERT INTO Disciplines VALUES('Football', 'M', 'Parc des Princes');
INSERT INTO Disciplines VALUES('Golf', 'F', 'Le Golf National');
INSERT INTO Disciplines VALUES('Golf', 'M', 'Le Golf National');
INSERT INTO Disciplines VALUES('Handball', 'F', 'South Paris Arena 6');
INSERT INTO Disciplines VALUES('Handball', 'M', 'South Paris Arena 6');
INSERT INTO Disciplines VALUES('Hockey', 'M', 'Yves-du-Manoir Stadium');
INSERT INTO Disciplines VALUES('Hockey', 'F', 'Yves-du-Manoir Stadium');
INSERT INTO Disciplines VALUES('Judo', 'M', 'Champ-de-Mars Arena');
INSERT INTO Disciplines VALUES('Judo', 'F', 'Champ-de-Mars Arena');
INSERT INTO Disciplines VALUES('Marathon Swimming', 'M', 'Pont Alexandre III');
INSERT INTO Disciplines VALUES('Marathon Swimming', 'F', 'Pont Alexandre III');
INSERT INTO Disciplines VALUES('Modern Pentathlon', 'M', 'North Paris Arena');
INSERT INTO Disciplines VALUES('Modern Pentathlon', 'F', 'North Paris Arena');
INSERT INTO Disciplines VALUES('Rhythmic Gymnastics', 'M', 'La Chapelle Arena');
INSERT INTO Disciplines VALUES('Rhythmic Gymnastics', 'F', 'La Chapelle Arena');
INSERT INTO Disciplines VALUES('Rowing', 'M', 'Nautical St - Flat water');
INSERT INTO Disciplines VALUES('Rowing', 'F', 'Nautical St - Flat water');
INSERT INTO Disciplines VALUES('Sailing', 'M', 'Marseille Marina');
INSERT INTO Disciplines VALUES('Sailing', 'F', 'Marseille Marina');
INSERT INTO Disciplines VALUES('Shooting', 'M', 'SHO');
INSERT INTO Disciplines VALUES('Shooting', 'F', 'SHO');
INSERT INTO Disciplines VALUES('Skateboarding', 'F', 'La Concorde 4');
INSERT INTO Disciplines VALUES('Skateboarding', 'M', 'La Concorde 4');
INSERT INTO Disciplines VALUES('Sport Climbing', 'F', 'Le Bourget Climbing Venue');
INSERT INTO Disciplines VALUES('Sport Climbing', 'M', 'Le Bourget Climbing Venue');
INSERT INTO Disciplines VALUES('Surfing', 'F', 'Teahupo, Tahiti');
INSERT INTO Disciplines VALUES('Surfing', 'M', 'Teahupo, Tahiti');
INSERT INTO Disciplines VALUES('Swimming', 'F', 'Paris La Defense Arena');
INSERT INTO Disciplines VALUES('Swimming', 'M', 'Paris La Defense Arena');
INSERT INTO Disciplines VALUES('Table Tennis', 'F', 'South Paris Arena 4');
INSERT INTO Disciplines VALUES('Table Tennis', 'M', 'South Paris Arena 4');
INSERT INTO Disciplines VALUES('Taekwondo', 'F', 'Grand Palais');
INSERT INTO Disciplines VALUES('Taekwondo', 'M', 'Grand Palais');
INSERT INTO Disciplines VALUES('Tennis', 'F', 'Roland-Garros Stadium');
INSERT INTO Disciplines VALUES('Tennis', 'M', 'Roland-Garros Stadium');
INSERT INTO Disciplines VALUES('Trampoline Gymnastics', 'F', 'Bercy Arena');
INSERT INTO Disciplines VALUES('Trampoline Gymnastics', 'M', 'Bercy Arena');
INSERT INTO Disciplines VALUES('Triathlon', 'M', 'Pont Alexandre III');
INSERT INTO Disciplines VALUES('Triathlon', 'F', 'Pont Alexandre III');
INSERT INTO Disciplines VALUES('Volleyball', 'M', 'South Paris Arena 1');
INSERT INTO Disciplines VALUES('Volleyball', 'F', 'South Paris Arena 1');
INSERT INTO Disciplines VALUES('Water Polo', 'M', 'Aquatics Centre');
INSERT INTO Disciplines VALUES('Water Polo', 'F', 'Aquatics Centre');
INSERT INTO Disciplines VALUES('Weightlifting', 'M', 'South Paris Arena 6');
INSERT INTO Disciplines VALUES('Weightlifting', 'F', 'South Paris Arena 6');
INSERT INTO Disciplines VALUES('Wrestling', 'M', 'Champ-de-Mars Arena');
INSERT INTO Disciplines VALUES('Wrestling', 'F', 'Champ-de-Mars Arena');




