INSERT INTO TechnicalOfficials VALUES('1536406', 'FRATINI Elisabetta', 'F', 'Referee', 'Judo');
INSERT INTO TechnicalOfficials VALUES('1550583', 'ILIC Corina', 'F', 'Referee', 'Judo');
INSERT INTO TechnicalOfficials VALUES('1550593', 'MAAFI Ziad', 'M', 'Referee', 'Judo');
INSERT INTO TechnicalOfficials VALUES('1550642', 'FUMEA Maria', 'F', 'Judge', '"Artistic Gymnastics');
INSERT INTO TechnicalOfficials VALUES('1550643', 'LEUNG Li Li', 'F', 'Judge', '"Artistic Gymnastics');
INSERT INTO TechnicalOfficials VALUES('1550645', 'MIAO Zhongyi', 'M', 'Judge', '"Artistic Gymnastics');
INSERT INTO TechnicalOfficials VALUES('1550646', 'VALENZO AOKI Naomi Chieko', 'F', 'Judge', '"Artistic Gymnastics');
INSERT INTO TechnicalOfficials VALUES('1550647', 'AL HITMI Ali', 'M', 'Judge', '"Artistic Gymnastics');
INSERT INTO TechnicalOfficials VALUES('1550648', 'AL TABBAA Mouhammed Youssef', 'M', 'Judge', '"Artistic Gymnastics');
INSERT INTO TechnicalOfficials VALUES('1550649', 'CELEN Suat', 'M', 'Judge', '"Artistic Gymnastics');
INSERT INTO TechnicalOfficials VALUES('1550650', 'ESAWY Ehab', 'M', 'Judge', '"Artistic Gymnastics');
INSERT INTO TechnicalOfficials VALUES('1550651', 'YAGI KITAGAWA Tammy', 'F', 'Judge', '"Artistic Gymnastics');
INSERT INTO TechnicalOfficials VALUES('1550652', 'VALERIO Rogerio', 'M', 'Judge', '"Artistic Gymnastics');
INSERT INTO TechnicalOfficials VALUES('1550653', 'MOWBRAY Denis', 'M', 'Judge', '"Artistic Gymnastics');
INSERT INTO TechnicalOfficials VALUES('1550654', 'PEGAN Aljaz', 'M', 'Judge', '"Artistic Gymnastics');
INSERT INTO TechnicalOfficials VALUES('1550655', 'PENICHE FRANCO Alejandro', 'M', 'Judge', '"Artistic Gymnastics');
INSERT INTO TechnicalOfficials VALUES('1550656', 'PERRIERE Charles', 'M', 'Judge', '"Artistic Gymnastics');
INSERT INTO TechnicalOfficials VALUES('1550657', 'TAEYMANS Rosy', 'F', 'Judge', '"Artistic Gymnastics');
INSERT INTO TechnicalOfficials VALUES('1550662', 'ACOSTA RODRIGUEZ Laura Patricia', 'F', 'Judge', 'Rhythmic Gymnastics');
INSERT INTO TechnicalOfficials VALUES('1550672', 'BEDOSHVILI Eliso', 'F', 'Judge', 'Rhythmic Gymnastics');
INSERT INTO TechnicalOfficials VALUES('1550674', 'BOJAKOWSKI Konrad', 'M', 'Judge', 'Trampoline Gymnastics');
INSERT INTO TechnicalOfficials VALUES('1550675', 'BOUROVA Roumiana', 'F', 'Judge', 'Rhythmic Gymnastics');
INSERT INTO TechnicalOfficials VALUES('1550689', 'DEUTSCH LAZSANYI Erika', 'F', 'Judge', 'Rhythmic Gymnastics');
INSERT INTO TechnicalOfficials VALUES('1550693', 'FILIPSKY Rebecca', 'F', 'Judge', 'Trampoline Gymnastics');
INSERT INTO TechnicalOfficials VALUES('1550694', 'GAIDA Viola', 'F', 'Judge', 'Trampoline Gymnastics');
INSERT INTO TechnicalOfficials VALUES('1550695', 'OLIVEIRA Joao', 'M', 'Judge', 'Trampoline Gymnastics');
INSERT INTO TechnicalOfficials VALUES('1550700', 'HALMU Delia', 'F', 'Judge', 'Rhythmic Gymnastics');
INSERT INTO TechnicalOfficials VALUES('1550707', 'JONES Andrew', 'M', 'Judge', 'Trampoline Gymnastics');
INSERT INTO TechnicalOfficials VALUES('1550709', 'KHOPERIA Rusudan', 'F', 'Judge', 'Trampoline Gymnastics');
INSERT INTO TechnicalOfficials VALUES('1550715', 'LHER Catherine Marie Andree', 'F', 'Judge', 'Rhythmic Gymnastics');
INSERT INTO TechnicalOfficials VALUES('1550723', 'MLEJNKOVA Blanka', 'F', 'Judge', 'Rhythmic Gymnastics');
INSERT INTO TechnicalOfficials VALUES('1550724', 'MROZINSKA Anna', 'F', 'Judge', 'Rhythmic Gymnastics');
INSERT INTO TechnicalOfficials VALUES('1550725', 'NAVA ACEVES Paulina', 'F', 'Judge', 'Trampoline Gymnastics');
INSERT INTO TechnicalOfficials VALUES('1550729', 'PAZOS SANCHEZ RUBIO Maria Inmacula.', 'F', 'Judge', 'Trampoline Gymnastics');
INSERT INTO TechnicalOfficials VALUES('1550730', 'PITKANEN Saila', 'F', 'Judge', 'Rhythmic Gymnastics');
INSERT INTO TechnicalOfficials VALUES('1550736', 'REHOROVA Martina', 'F', 'Judge', 'Trampoline Gymnastics');
INSERT INTO TechnicalOfficials VALUES('1550753', 'SUZUKI Aoi', 'F', 'Judge', 'Rhythmic Gymnastics');
INSERT INTO TechnicalOfficials VALUES('1550762', 'van WETERING Babette', 'F', 'Judge', 'Trampoline Gymnastics');
INSERT INTO TechnicalOfficials VALUES('1550763', 'VANGELOVA Mariya', 'F', 'Judge', 'Trampoline Gymnastics');
INSERT INTO TechnicalOfficials VALUES('1550776', 'BEKTUROVA Alua', 'F', 'Judge', 'Rhythmic Gymnastics');
INSERT INTO TechnicalOfficials VALUES('1557225', 'STROOBANTS Marine', 'F', 'Referee', 'Judo');
INSERT INTO TechnicalOfficials VALUES('1560199', 'FISCHER Matthias', 'M', 'Referee', 'Judo');
INSERT INTO TechnicalOfficials VALUES('1560200', 'LAMPE Nusa', 'F', 'Referee', 'Judo');
INSERT INTO TechnicalOfficials VALUES('1560201', 'CHYURLIA Pasquale', 'M', 'Referee', 'Judo');
INSERT INTO TechnicalOfficials VALUES('1560211', 'FREITAS Leandra', 'F', 'Referee', 'Judo');
INSERT INTO TechnicalOfficials VALUES('1562036', 'SHMAKOV Vladimir', 'M', 'Referee', 'Judo');
INSERT INTO TechnicalOfficials VALUES('1562711', 'MIGLIORINI Sergio', 'M', 'Medical Delegate', 'Triathlon');
INSERT INTO TechnicalOfficials VALUES('1563015', 'BOUHEDDOU Mohamed', 'M', 'Referee', 'Judo');
INSERT INTO TechnicalOfficials VALUES('1563830', 'SZOKE Andor', 'M', 'Referee', 'Judo');
INSERT INTO TechnicalOfficials VALUES('1563872', 'GALEA Louisa', 'F', 'Referee', 'Judo');
INSERT INTO TechnicalOfficials VALUES('1563891', 'BILIC Miroslav', 'M', 'Referee', 'Judo');
INSERT INTO TechnicalOfficials VALUES('1563909', 'DELIU Denisa', 'F', 'Referee', 'Judo');
INSERT INTO TechnicalOfficials VALUES('1563980', 'BEREGSZASZI Zita', 'F', 'Referee', 'Judo');
INSERT INTO TechnicalOfficials VALUES('1564197', 'SANCHEZ del CAMPO Ana', 'F', 'Jury Chair', 'Sailing');
INSERT INTO TechnicalOfficials VALUES('1564543', 'WU Jingyu', 'F', 'Referee', 'Taekwondo');
INSERT INTO TechnicalOfficials VALUES('1564544', 'MAGABLEH Maher', 'M', 'Referee', 'Taekwondo');
INSERT INTO TechnicalOfficials VALUES('1564548', 'KIM Song Chul', 'M', 'Referee', 'Taekwondo');
INSERT INTO TechnicalOfficials VALUES('1566303', 'ANDERSEN Jacob', 'M', 'Jury Member', 'Sailing');
INSERT INTO TechnicalOfficials VALUES('1566308', 'FERRANDIZ RUIZ Luis', 'M', 'Jury Member', 'Sailing');
INSERT INTO TechnicalOfficials VALUES('1566313', 'NAPIER Jon', 'M', 'Jury Member', 'Sailing');
INSERT INTO TechnicalOfficials VALUES('1566318', 'HEREDIA Gonzalo', 'M', 'Jury Member', 'Sailing');
INSERT INTO TechnicalOfficials VALUES('1566319', 'YOVKOVA Iskra', 'F', 'Jury Member', 'Sailing');
INSERT INTO TechnicalOfficials VALUES('1566455', 'BOROCZ Bence', 'M', 'Jury Member', 'Sailing');
INSERT INTO TechnicalOfficials VALUES('1566468', 'JEONG Sungchul', 'M', 'Jury Member', 'Sailing');
INSERT INTO TechnicalOfficials VALUES('1566473', 'GROSVENOR Sandy', 'F', 'Jury Member', 'Sailing');
INSERT INTO TechnicalOfficials VALUES('1566474', 'GUERRA Rodrigo', 'M', 'Jury Member', 'Sailing');
INSERT INTO TechnicalOfficials VALUES('1566475', 'LEWANDOWSKA Anastazja', 'F', 'Jury Member', 'Sailing');
INSERT INTO TechnicalOfficials VALUES('1566476', 'LINDSAY Chris', 'M', 'Jury Member', 'Sailing');
INSERT INTO TechnicalOfficials VALUES('1566480', 'MOOKKEN Selvam', 'M', 'Jury Member', 'Sailing');
INSERT INTO TechnicalOfficials VALUES('1566482', 'ORTENDAHL Christina', 'F', 'Jury Member', 'Sailing');
INSERT INTO TechnicalOfficials VALUES('1566488', 'SCOTT Luke', 'M', 'Jury Member', 'Sailing');
INSERT INTO TechnicalOfficials VALUES('1566489', 'STANIKIC Mina', 'F', 'Jury Member', 'Sailing');
INSERT INTO TechnicalOfficials VALUES('1570413', 'D''URBANO Francesco Jacopo', 'M', 'Judge', 'Skateboarding');
INSERT INTO TechnicalOfficials VALUES('1571122', 'ALSHATHRI A Rahman', 'M', 'Judge', '"Artistic Gymnastics');
INSERT INTO TechnicalOfficials VALUES('1571123', 'KIM Nellia', 'F', 'Judge', '"Artistic Gymnastics');
INSERT INTO TechnicalOfficials VALUES('1571124', 'TITOV Vasilii', 'M', 'Judge', '"Artistic Gymnastics');
INSERT INTO TechnicalOfficials VALUES('1571143', 'ALIPRANDI Elena', 'F', 'Judge', 'Rhythmic Gymnastics');
INSERT INTO TechnicalOfficials VALUES('1571146', 'DRAGAS Spela', 'F', 'Judge', 'Rhythmic Gymnastics');
INSERT INTO TechnicalOfficials VALUES('1571149', 'IEROMINA Nataliia', 'F', 'Judge', 'Rhythmic Gymnastics');
INSERT INTO TechnicalOfficials VALUES('1893012', 'CHIARI Roberto', 'M', 'Referee', 'Basketball');
INSERT INTO TechnicalOfficials VALUES('1893016', 'THOMSON Mike', 'M', 'Referee', 'Basketball');
INSERT INTO TechnicalOfficials VALUES('1893040', 'DUPUCHE Crystal', 'F', 'Referee', 'Basketball');
INSERT INTO TechnicalOfficials VALUES('1893057', 'VAQUERA Alejandro', 'M', 'Referee', 'Basketball');
INSERT INTO TechnicalOfficials VALUES('1893105', 'SHAFAGHI Shahrad', 'M', 'Referee', 'Basketball');
INSERT INTO TechnicalOfficials VALUES('1893111', 'KAUPPINEN Hannu', 'M', 'Referee', 'Basketball');
INSERT INTO TechnicalOfficials VALUES('1893239', 'CASTRO Antonio', 'M', 'Referee', 'Judo');
INSERT INTO TechnicalOfficials VALUES('1893241', 'MURADOV Abdullo', 'M', 'Referee', 'Judo');
INSERT INTO TechnicalOfficials VALUES('1894925', 'AMANTINO Giseli', 'F', 'Referee', 'Beach Volleyball');
INSERT INTO TechnicalOfficials VALUES('1894929', 'BOCK Stephen', 'M', 'Referee', 'Volleyball');
INSERT INTO TechnicalOfficials VALUES('1894942', 'CARVALHO Rui Jorge', 'M', 'Referee', 'Beach Volleyball');
INSERT INTO TechnicalOfficials VALUES('1894943', 'HIEBERT Brian', 'M', 'Referee', 'Beach Volleyball');
INSERT INTO TechnicalOfficials VALUES('1894944', 'RENE Karina', 'F', 'Referee', 'Volleyball');
INSERT INTO TechnicalOfficials VALUES('1894975', 'CRESCENTINI Davide', 'M', 'Referee', 'Beach Volleyball');
INSERT INTO TechnicalOfficials VALUES('1894976', 'SIMONOVIC Vladimir', 'M', 'Referee', 'Volleyball');
INSERT INTO TechnicalOfficials VALUES('1894978', 'WANG Lijun', 'F', 'Referee', 'Beach Volleyball');
INSERT INTO TechnicalOfficials VALUES('1894979', 'BEATIE Brigham', 'M', 'Referee', 'Beach Volleyball');
INSERT INTO TechnicalOfficials VALUES('1895002', 'SATOMI Mariko', 'F', 'Referee', 'Beach Volleyball');
INSERT INTO TechnicalOfficials VALUES('1895006', 'SAAVEDRA CACERES Juan Carlos', 'M', 'Referee', 'Beach Volleyball');
INSERT INTO TechnicalOfficials VALUES('1895007', 'OZBAR Nurper', 'F', 'Referee', 'Volleyball');
INSERT INTO TechnicalOfficials VALUES('1895009', 'IVANOV Ivaylo', 'M', 'Referee', 'Volleyball');
INSERT INTO TechnicalOfficials VALUES('1895011', 'DRUART Sylvain', 'M', 'Referee', 'Beach Volleyball');
INSERT INTO TechnicalOfficials VALUES('1895012', 'MYSZKOWSKA Agnieszka', 'F', 'Referee', 'Beach Volleyball');
INSERT INTO TechnicalOfficials VALUES('1895013', 'PAPADOGOULAS Charalampos', 'M', 'Referee', 'Beach Volleyball');
INSERT INTO TechnicalOfficials VALUES('1895017', 'CESARE Stefano', 'M', 'Referee', 'Volleyball');
INSERT INTO TechnicalOfficials VALUES('1895018', 'LEKO Robert', 'M', 'Referee', 'Beach Volleyball');
INSERT INTO TechnicalOfficials VALUES('1895019', 'GUILLEMETTE Lucie', 'F', 'Challenge Referee', 'Beach Volleyball');
INSERT INTO TechnicalOfficials VALUES('1895020', 'GRASS Angela', 'F', 'Referee', 'Volleyball');
INSERT INTO TechnicalOfficials VALUES('1895021', 'KANDIL Wael', 'M', 'Referee', 'Volleyball');
INSERT INTO TechnicalOfficials VALUES('1895022', 'BENNETT John', 'M', 'Challenge Referee', 'Beach Volleyball');
INSERT INTO TechnicalOfficials VALUES('1895023', 'MOKRY Juraj', 'M', 'Referee', 'Volleyball');
INSERT INTO TechnicalOfficials VALUES('1895025', 'COLLADOS Fabrice', 'M', 'Referee', 'Volleyball');
INSERT INTO TechnicalOfficials VALUES('1895026', 'RAPISARDA Daniele', 'M', 'Challenge Referee', 'Volleyball');
INSERT INTO TechnicalOfficials VALUES('1895027', 'BOUDAYA Taoufik', 'M', 'Challenge Referee', 'Volleyball');
INSERT INTO TechnicalOfficials VALUES('1895028', 'ALROUSI ALHAMMADI Hamid Mohamed Ah.', 'M', 'Referee', 'Volleyball');
INSERT INTO TechnicalOfficials VALUES('1895031', 'GEROTHODOROS Epaminondas', 'M', 'Referee', 'Volleyball');
INSERT INTO TechnicalOfficials VALUES('1895034', 'SUMAVIL Osvaldo', 'M', 'Referee', 'Beach Volleyball');
INSERT INTO TechnicalOfficials VALUES('1895035', 'BRONISZ Robert', 'M', 'Challenge Referee', 'Beach Volleyball');
INSERT INTO TechnicalOfficials VALUES('1895037', 'CESPEDES Denny', 'M', 'Referee', 'Volleyball');
INSERT INTO TechnicalOfficials VALUES('1895038', 'DZIEWIRZ Scott', 'M', 'Referee', 'Volleyball');
INSERT INTO TechnicalOfficials VALUES('1895040', 'PADRON Jose Maria', 'M', 'Referee', 'Beach Volleyball');
INSERT INTO TechnicalOfficials VALUES('1895042', 'MAROSZEK Wojciech', 'M', 'Referee', 'Volleyball');
INSERT INTO TechnicalOfficials VALUES('1895047', 'MYOI Sumie', 'F', 'Referee', 'Volleyball');
INSERT INTO TechnicalOfficials VALUES('1895048', 'MUKUNDIYUKURI Jean de Dieu', 'M', 'Referee', 'Beach Volleyball');
INSERT INTO TechnicalOfficials VALUES('1897318', 'CSOSZ Imre', 'M', 'Referee', 'Judo');
INSERT INTO TechnicalOfficials VALUES('1898273', 'HUNT Patrick', 'M', 'Jury Member', 'Basketball');
INSERT INTO TechnicalOfficials VALUES('1898633', 'AL SHUWAILI Ahmed', 'M', 'Referee', 'Basketball');
INSERT INTO TechnicalOfficials VALUES('1898640', 'ANAYA Julio', 'M', 'Referee', 'Basketball');
INSERT INTO TechnicalOfficials VALUES('1898648', 'BAKI Kerem', 'M', 'Referee', 'Basketball');
INSERT INTO TechnicalOfficials VALUES('1898669', 'BARTEL Andres', 'M', 'Referee', 'Basketball');
INSERT INTO TechnicalOfficials VALUES('1898675', 'BATISTA Johnny', 'M', 'Referee', 'Basketball');
INSERT INTO TechnicalOfficials VALUES('1898693', 'BEKER Scott', 'M', 'Referee', 'Basketball');
INSERT INTO TechnicalOfficials VALUES('1898701', 'BERMUDEZ Omar', 'M', 'Referee', 'Basketball');
INSERT INTO TechnicalOfficials VALUES('1898712', 'BONNER Amy', 'F', 'Referee', 'Basketball');
INSERT INTO TechnicalOfficials VALUES('1898728', 'BURNS Blanca', 'F', 'Referee', 'Basketball');
INSERT INTO TechnicalOfficials VALUES('1898782', 'CASTILLO Luis', 'M', 'Referee', 'Basketball');
INSERT INTO TechnicalOfficials VALUES('1898799', 'CHUECA Ariadna', 'F', 'Referee', 'Basketball');
INSERT INTO TechnicalOfficials VALUES('1898911', 'CONDE Antonio', 'M', 'Referee', 'Basketball');
INSERT INTO TechnicalOfficials VALUES('1899120', 'SUTHERLAND Jamie', 'M', 'Jury Member', 'Sailing');
INSERT INTO TechnicalOfficials VALUES('1899125', 'TANAKA Masaaki', 'M', 'Jury Member', 'Sailing');
INSERT INTO TechnicalOfficials VALUES('1899135', 'WILMINK E V den BURGER Pauline', 'F', 'Jury Member', 'Sailing');
INSERT INTO TechnicalOfficials VALUES('1906878', 'SMAK Wouter', 'M', 'Judge', 'Cycling BMX Freestyle');
INSERT INTO TechnicalOfficials VALUES('1916068', 'MORARD Tristan', 'M', 'Referee', 'Wrestling');
INSERT INTO TechnicalOfficials VALUES('1916391', 'VILLET Charles', 'M', 'Referee', 'Wrestling');
INSERT INTO TechnicalOfficials VALUES('1916453', 'BARGAILA Deividas', 'M', 'Referee', 'Wrestling');
INSERT INTO TechnicalOfficials VALUES('1916503', 'VEYRAT Emmanuel', 'M', 'Referee', 'Wrestling');
INSERT INTO TechnicalOfficials VALUES('1916629', 'BOUAZIZ Youssef', 'M', 'Referee', 'Wrestling');
INSERT INTO TechnicalOfficials VALUES('1916804', 'MENKOVAS Kirilas', 'M', 'Referee', 'Wrestling');
INSERT INTO TechnicalOfficials VALUES('1916826', 'NEDELJKOVIC Leonardo', 'M', 'Referee', 'Wrestling');
INSERT INTO TechnicalOfficials VALUES('1916838', 'BORJANOVIC Borislav', 'M', 'Referee', 'Wrestling');
INSERT INTO TechnicalOfficials VALUES('1920697', 'CHIASSON Marcia', 'F', 'Referee', 'Wrestling');
INSERT INTO TechnicalOfficials VALUES('1920703', 'KOUTSOPODIOTIS Demetra', 'F', 'Referee', 'Wrestling');
INSERT INTO TechnicalOfficials VALUES('1920739', 'SUN Jian', 'M', 'Referee', 'Wrestling');
INSERT INTO TechnicalOfficials VALUES('1920745', 'OCIC Zvonko', 'M', 'Referee', 'Wrestling');
INSERT INTO TechnicalOfficials VALUES('1921064', 'SCHEINER Vaclav', 'M', 'Referee', 'Wrestling');
INSERT INTO TechnicalOfficials VALUES('1921117', 'HIETALA Joonas', 'M', 'Referee', 'Wrestling');
INSERT INTO TechnicalOfficials VALUES('1921173', 'TRAN Melanie', 'F', 'Referee', 'Wrestling');
INSERT INTO TechnicalOfficials VALUES('1922135', 'JIBLADZE Zaza', 'M', 'Referee', 'Wrestling');
INSERT INTO TechnicalOfficials VALUES('1922182', 'SCHERER Ramona', 'F', 'Referee', 'Wrestling');
INSERT INTO TechnicalOfficials VALUES('1922183', 'DAHRA Amel', 'F', 'Referee', 'Basketball');
INSERT INTO TechnicalOfficials VALUES('1922369', 'DAVIDSON Yann', 'M', 'Referee', 'Basketball');
INSERT INTO TechnicalOfficials VALUES('1922392', 'SCHMITT Karl Peter', 'M', 'Referee', 'Wrestling');
INSERT INTO TechnicalOfficials VALUES('1922396', 'FERNANDEZ Juan', 'M', 'Referee', 'Basketball');
INSERT INTO TechnicalOfficials VALUES('1922427', 'GEORGIOU Pavlina', 'F', 'Referee', 'Wrestling');
INSERT INTO TechnicalOfficials VALUES('1922432', 'FORSBERG Maj', 'F', 'Referee', 'Basketball');
INSERT INTO TechnicalOfficials VALUES('1922550', 'GYORGYI Viola', 'F', 'Referee', 'Basketball');
INSERT INTO TechnicalOfficials VALUES('1922553', 'LIAKOS Christos', 'M', 'Referee', 'Wrestling');
INSERT INTO TechnicalOfficials VALUES('1922569', 'KALLIO Matthew', 'M', 'Referee', 'Basketball');
INSERT INTO TechnicalOfficials VALUES('1922570', 'SLEISZ Gabriella', 'F', 'Referee', 'Wrestling');
INSERT INTO TechnicalOfficials VALUES('1922591', 'KATO Takaki', 'M', 'Referee', 'Basketball');
INSERT INTO TechnicalOfficials VALUES('1922614', 'KOZLOVSKIS Martins', 'M', 'Referee', 'Basketball');
INSERT INTO TechnicalOfficials VALUES('1922689', 'KREJIC Boris', 'M', 'Referee', 'Basketball');
INSERT INTO TechnicalOfficials VALUES('1923016', 'LEE Jiwoo', 'F', 'Referee', 'Wrestling');
INSERT INTO TechnicalOfficials VALUES('1927242', 'WARWICK Richard Jaydes', 'M', 'Referee', 'Taekwondo');
INSERT INTO TechnicalOfficials VALUES('1928960', 'LISZKA Wojciech', 'M', 'Referee', 'Basketball');
INSERT INTO TechnicalOfficials VALUES('1929700', 'TOOLEY Jim', 'M', 'Jury Member', 'Basketball');
INSERT INTO TechnicalOfficials VALUES('1929719', 'BRENSCHEIDT Wolfgang', 'M', 'Jury Member', 'Basketball');
INSERT INTO TechnicalOfficials VALUES('1929775', 'BARTLETT Michael', 'M', 'Jury Member', 'Basketball');
INSERT INTO TechnicalOfficials VALUES('1932965', 'CAMACHO IBARRA Juan Arturo', 'M', 'Referee', 'Wrestling');
INSERT INTO TechnicalOfficials VALUES('1933080', 'ABDOELAEV Edmar', 'M', 'Referee', 'Wrestling');
INSERT INTO TechnicalOfficials VALUES('1933098', 'HAMMER Thomas', 'M', 'Referee', 'Wrestling');
INSERT INTO TechnicalOfficials VALUES('1933258', 'GALVA LEBRON Rafael Abraham', 'M', 'Referee', 'Wrestling');
INSERT INTO TechnicalOfficials VALUES('1933271', 'CIMPOERU Marius', 'M', 'Referee', 'Wrestling');
INSERT INTO TechnicalOfficials VALUES('1933310', 'TORBICA Nikola', 'M', 'Referee', 'Wrestling');
INSERT INTO TechnicalOfficials VALUES('1933349', 'SJOSTROM Linn', 'F', 'Referee', 'Wrestling');
INSERT INTO TechnicalOfficials VALUES('1933383', 'SHADGAN Babak', 'M', 'Referee', 'Wrestling');
INSERT INTO TechnicalOfficials VALUES('1933394', 'GARCIA Carlos', 'M', 'Referee', 'Wrestling');
INSERT INTO TechnicalOfficials VALUES('1933402', 'SILVESTRI Antonio', 'M', 'Referee', 'Wrestling');
INSERT INTO TechnicalOfficials VALUES('1933411', 'KOIKE Kuninori', 'M', 'Referee', 'Wrestling');
INSERT INTO TechnicalOfficials VALUES('1934331', 'KARAS Martin', 'M', 'Judge', 'Skateboarding');
INSERT INTO TechnicalOfficials VALUES('1934350', 'IWAKATA Rieko', 'F', 'Judge', 'Skateboarding');
INSERT INTO TechnicalOfficials VALUES('1934369', 'SANCHEZ Natalia', 'F', 'Judge', 'Skateboarding');
INSERT INTO TechnicalOfficials VALUES('1934479', 'PICCOLO Ilaria', 'F', 'Judge', 'Skateboarding');
INSERT INTO TechnicalOfficials VALUES('1934504', 'SCHRODER Laura', 'F', 'Judge', 'Skateboarding');
INSERT INTO TechnicalOfficials VALUES('1937668', 'KONSTANTINOU Loukas', 'M', 'Referee', 'Wrestling');
INSERT INTO TechnicalOfficials VALUES('1937682', 'GYARMATI Ferenc', 'M', 'Referee', 'Wrestling');
INSERT INTO TechnicalOfficials VALUES('1937701', 'MESSER KERSTING Thomas', 'M', 'Referee', '"3x3 Basketball');
INSERT INTO TechnicalOfficials VALUES('1937705', 'SERNEK Stanislav', 'M', 'Referee', 'Wrestling');
INSERT INTO TechnicalOfficials VALUES('1937758', 'BERTRAND Eric', 'M', 'Referee', '3x3 Basketball');
INSERT INTO TechnicalOfficials VALUES('1937785', 'HO Edmond', 'M', 'Referee', '3x3 Basketball');
INSERT INTO TechnicalOfficials VALUES('1937791', 'JANG Tsong Rong', 'M', 'Referee', 'Wrestling');
INSERT INTO TechnicalOfficials VALUES('1937815', 'MICHAELIDES Markos-Elias', 'M', 'Referee', '3x3 Basketball');
INSERT INTO TechnicalOfficials VALUES('1937848', 'MALISZEWSKI Marek', 'M', 'Referee', '3x3 Basketball');
INSERT INTO TechnicalOfficials VALUES('1937858', 'CHAJIDDINE Najib', 'M', 'Referee', '3x3 Basketball');
INSERT INTO TechnicalOfficials VALUES('1937879', 'GHIZDAREANU Vlad', 'M', 'Referee', '3x3 Basketball');
INSERT INTO TechnicalOfficials VALUES('1937882', 'GOESSL Casey', 'M', 'Referee', 'Wrestling');
INSERT INTO TechnicalOfficials VALUES('1937884', 'JURAS Jasmina', 'F', 'Referee', '3x3 Basketball');
INSERT INTO TechnicalOfficials VALUES('1937897', 'BOUAZIZ Mohamed Kamel', 'M', 'Referee', 'Wrestling');
INSERT INTO TechnicalOfficials VALUES('1937903', 'SHI Qirong', 'F', 'Referee', '3x3 Basketball');
INSERT INTO TechnicalOfficials VALUES('1937919', 'KIM Gain', 'F', 'Referee', '3x3 Basketball');
INSERT INTO TechnicalOfficials VALUES('1937973', 'CSABAI-KASKOTO Brigitta', 'F', 'Referee', '3x3 Basketball');
INSERT INTO TechnicalOfficials VALUES('1937982', 'OKATCH Dorothy', 'F', 'Referee', '3x3 Basketball');
INSERT INTO TechnicalOfficials VALUES('1937992', 'NEUMANN Aleisha', 'F', 'Umpire', 'Hockey');
INSERT INTO TechnicalOfficials VALUES('1937993', 'KEOGH Alison', 'F', 'Umpire', 'Hockey');
INSERT INTO TechnicalOfficials VALUES('1937994', 'CHURCH Amber', 'F', 'Umpire', 'Hockey');
INSERT INTO TechnicalOfficials VALUES('1937996', 'McCLEAN Ayanna', 'F', 'Umpire', 'Hockey');
INSERT INTO TechnicalOfficials VALUES('1938000', 'TAN Cookie', 'F', 'Umpire', 'Hockey');
INSERT INTO TechnicalOfficials VALUES('1938001', 'BARSTOW Daniel', 'M', 'Umpire', 'Hockey');
INSERT INTO TechnicalOfficials VALUES('1938002', 'TOMLINSON David', 'M', 'Umpire', 'Hockey');
INSERT INTO TechnicalOfficials VALUES('1938004', 'YAMADA Emi', 'F', 'Umpire', 'Hockey');
INSERT INTO TechnicalOfficials VALUES('1938006', 'LABATE Gabriel', 'M', 'Umpire', 'Hockey');
INSERT INTO TechnicalOfficials VALUES('1938007', 'GREENFIELD Gareth', 'M', 'Umpire', 'Hockey');
INSERT INTO TechnicalOfficials VALUES('1938008', 'HARRISON Hannah', 'F', 'Umpire', 'Hockey');
INSERT INTO TechnicalOfficials VALUES('1938009', 'LIM Hong Zhen', 'M', 'Umpire', 'Hockey');
INSERT INTO TechnicalOfficials VALUES('1938010', 'PRESENQUI Irene', 'F', 'Umpire', 'Hockey');
INSERT INTO TechnicalOfficials VALUES('1938013', 'JACKSON Deanna', 'F', 'Referee', '3x3 Basketball');
INSERT INTO TechnicalOfficials VALUES('1938014', 'VAN''T HEK Jonas', 'M', 'Umpire', 'Hockey');
INSERT INTO TechnicalOfficials VALUES('1938015', 'van BUNGE Coen', 'M', 'Umpire', 'Hockey');
INSERT INTO TechnicalOfficials VALUES('1938016', 'DELFORGE Laurine', 'F', 'Umpire', 'Hockey');
INSERT INTO TechnicalOfficials VALUES('1938019', 'GROCHAL Marcin', 'M', 'Umpire', 'Hockey');
INSERT INTO TechnicalOfficials VALUES('1938022', 'MADDEN Martin', 'M', 'Umpire', 'Hockey');
INSERT INTO TechnicalOfficials VALUES('1938024', 'WILLIAMS Rachel', 'F', 'Umpire', 'Hockey');
INSERT INTO TechnicalOfficials VALUES('1938030', 'WILSON Sarah', 'F', 'Umpire', 'Hockey');
INSERT INTO TechnicalOfficials VALUES('1938032', 'ROGERS Steve', 'M', 'Umpire', 'Hockey');
INSERT INTO TechnicalOfficials VALUES('1938039', 'KIREZIEV Nedyalko Kirov', 'M', 'Referee', 'Wrestling');
INSERT INTO TechnicalOfficials VALUES('1938090', 'TALISAINEN Alex', 'M', 'Referee', '3x3 Basketball');
INSERT INTO TechnicalOfficials VALUES('1938097', 'JULIAN Samuel', 'M', 'Referee', 'Wrestling');
INSERT INTO TechnicalOfficials VALUES('1938099', 'CSENDER Andrada Monika', 'F', 'Referee', '3x3 Basketball');
INSERT INTO TechnicalOfficials VALUES('1938104', 'VESKOVIC Vladimir', 'M', 'Referee', '3x3 Basketball');
INSERT INTO TechnicalOfficials VALUES('1938105', 'SYLSTAD Susanna', 'F', 'Referee', 'Wrestling');
INSERT INTO TechnicalOfficials VALUES('1938619', 'CICIOGLU Ibrahim', 'M', 'Referee', 'Wrestling');
INSERT INTO TechnicalOfficials VALUES('1940919', 'YUCEL Mehmet Gurhan', 'M', 'Referee', 'Wrestling');
INSERT INTO TechnicalOfficials VALUES('1941133', 'BASHIRZADEH NAMADMAL Mehdi', 'M', 'Referee', 'Wrestling');
INSERT INTO TechnicalOfficials VALUES('1941151', 'BLATT Scott', 'M', 'Judge', 'Cycling BMX Freestyle');
INSERT INTO TechnicalOfficials VALUES('1941720', 'JAZBINSEK Marko', 'M', 'Judge', 'Skateboarding');
INSERT INTO TechnicalOfficials VALUES('1941779', 'DILLEWAARD Dave', 'M', 'Judge', 'Cycling BMX Freestyle');
INSERT INTO TechnicalOfficials VALUES('1941791', 'CLEWORTH David', 'M', 'Head Judge', 'Cycling BMX Freestyle');
INSERT INTO TechnicalOfficials VALUES('1942348', 'NIEVAS Alhambra', 'F', 'Referee', 'Rugby Sevens');
INSERT INTO TechnicalOfficials VALUES('1942350', 'BLANCO Juan Cruz', 'M', 'Referee', 'Rugby Sevens');
INSERT INTO TechnicalOfficials VALUES('1942353', 'VENTER Wanri', 'F', 'Umpire', 'Hockey');
INSERT INTO TechnicalOfficials VALUES('1942354', 'LEAL Adam', 'M', 'Referee', 'Rugby Sevens');
INSERT INTO TechnicalOfficials VALUES('1942356', 'JUMA James', 'M', 'Referee', 'Rugby Sevens');
INSERT INTO TechnicalOfficials VALUES('1942360', 'JOUBERT Craig Paul', 'M', 'Referee', 'Rugby Sevens');
INSERT INTO TechnicalOfficials VALUES('1942361', 'MATTHEWS Fran', 'F', 'Referee', 'Rugby Sevens');
INSERT INTO TechnicalOfficials VALUES('1942363', 'JOHNSTON Matthew', 'M', 'Referee', 'Rugby Sevens');
INSERT INTO TechnicalOfficials VALUES('1942365', 'MATSUO Amy', 'F', 'Referee', 'Rugby Sevens');
INSERT INTO TechnicalOfficials VALUES('1942367', 'NOLAN Yvonne', 'F', 'Referee', 'Rugby Sevens');
INSERT INTO TechnicalOfficials VALUES('1942368', 'FERGUSON Peter', 'M', 'Referee', 'Rugby Sevens');
INSERT INTO TechnicalOfficials VALUES('1942369', 'O''DWYER Carmel', 'F', 'Referee', 'Rugby Sevens');
INSERT INTO TechnicalOfficials VALUES('1942370', 'DONAGHER Ronan', 'M', 'Referee', 'Rugby Sevens');
INSERT INTO TechnicalOfficials VALUES('1942371', 'O''BRIEN Paddy', 'M', 'Referee', 'Rugby Sevens');
INSERT INTO TechnicalOfficials VALUES('1942372', 'QUINLAN Christopher', 'M', 'Referee', 'Rugby Sevens');
INSERT INTO TechnicalOfficials VALUES('1942373', 'KEANE David', 'M', 'Referee', 'Rugby Sevens');
INSERT INTO TechnicalOfficials VALUES('1942374', 'TWOMEY Cian', 'M', 'Referee', 'Rugby Sevens');
INSERT INTO TechnicalOfficials VALUES('1942375', 'GNECCHI Gianluca', 'M', 'Referee', 'Rugby Sevens');
INSERT INTO TechnicalOfficials VALUES('1942376', 'DICKENS Beth', 'F', 'Referee', 'Rugby Sevens');
INSERT INTO TechnicalOfficials VALUES('1942377', 'ROZIER Jeremy', 'M', 'Referee', 'Rugby Sevens');
INSERT INTO TechnicalOfficials VALUES('1942378', 'WARD David', 'M', 'Referee', 'Rugby Sevens');
INSERT INTO TechnicalOfficials VALUES('1942379', 'ROKOVERENI Tevita', 'M', 'Referee', 'Rugby Sevens');
INSERT INTO TechnicalOfficials VALUES('1942380', 'McPHAIL James', 'M', 'Referee', 'Rugby Sevens');
INSERT INTO TechnicalOfficials VALUES('1942972', 'WANG Ziling', 'F', 'Referee', 'Volleyball');
INSERT INTO TechnicalOfficials VALUES('1943350', 'HUGHES Christi', 'F', 'Judge', 'Cycling BMX Freestyle');
INSERT INTO TechnicalOfficials VALUES('1943476', 'RAPAPORT Sean', 'M', 'Umpire', 'Hockey');
INSERT INTO TechnicalOfficials VALUES('1948013', 'ROSTRON Annelize', 'F', 'Umpire', 'Hockey');
INSERT INTO TechnicalOfficials VALUES('1948034', 'PRASAD Raghu', 'M', 'Umpire', 'Hockey');
INSERT INTO TechnicalOfficials VALUES('1948172', 'MIKHEYEV Yevgeniy', 'M', 'Referee', 'Basketball');
INSERT INTO TechnicalOfficials VALUES('1948315', 'MOSTAFA Wael', 'M', 'Referee', 'Basketball');
INSERT INTO TechnicalOfficials VALUES('1948497', 'NOUJAIM Rabah', 'M', 'Referee', 'Basketball');
INSERT INTO TechnicalOfficials VALUES('1948922', 'PERALTA Carlos', 'M', 'Referee', 'Basketball');
INSERT INTO TechnicalOfficials VALUES('1949000', 'PAEZ Kristian', 'M', 'Referee', 'Basketball');
INSERT INTO TechnicalOfficials VALUES('1949352', 'JURGENS Axel', 'M', 'Judge', 'Cycling BMX Freestyle');
INSERT INTO TechnicalOfficials VALUES('1956115', 'KACHINSKY Brian', 'M', 'Judge', 'Cycling BMX Freestyle');
INSERT INTO TechnicalOfficials VALUES('1956714', 'NOIROT Romuald', 'M', 'Judge', 'Cycling BMX Freestyle');
INSERT INTO TechnicalOfficials VALUES('1957925', 'TOSI Fulvia', 'F', 'Judge', 'Cycling BMX Freestyle');
INSERT INTO TechnicalOfficials VALUES('1958435', 'McGARRIGLE Ben', 'M', 'Referee', 'Boxing');
INSERT INTO TechnicalOfficials VALUES('1958462', 'REESE Shawn', 'M', 'Referee', 'Boxing');
INSERT INTO TechnicalOfficials VALUES('1958696', 'ALTAYEV Alisher', 'M', 'Referee', 'Boxing');
INSERT INTO TechnicalOfficials VALUES('1958816', 'MOUHNI Abderrazzak', 'M', 'Referee', 'Boxing');
INSERT INTO TechnicalOfficials VALUES('1958835', 'BABANLI Anar', 'M', 'Judge', 'Boxing');
INSERT INTO TechnicalOfficials VALUES('1958863', 'FERREIRA Emanuel', 'M', 'Referee', 'Boxing');
INSERT INTO TechnicalOfficials VALUES('1958875', 'PASTOR ARREAGA Emerson Alejandro', 'M', 'Referee', 'Boxing');
INSERT INTO TechnicalOfficials VALUES('1959180', 'SCHNEIDER Jill', 'F', 'Jury Member', 'Basketball');
INSERT INTO TechnicalOfficials VALUES('1963610', 'PRAKSCH Peter', 'M', 'Referee', 'Basketball');
INSERT INTO TechnicalOfficials VALUES('1963689', 'RENEAU Jenna', 'F', 'Referee', 'Basketball');
INSERT INTO TechnicalOfficials VALUES('1963755', 'ROSSO Yohan', 'M', 'Referee', 'Basketball');
INSERT INTO TechnicalOfficials VALUES('1963769', 'SALINS Gatis', 'M', 'Referee', 'Basketball');
INSERT INTO TechnicalOfficials VALUES('1963784', 'VAZQUEZ Roberto', 'M', 'Referee', 'Basketball');
INSERT INTO TechnicalOfficials VALUES('1963816', 'VULIC Martin', 'M', 'Referee', 'Basketball');
INSERT INTO TechnicalOfficials VALUES('1963832', 'ZURAPOVIC Ademir', 'M', 'Referee', 'Basketball');
INSERT INTO TechnicalOfficials VALUES('1963904', 'MALO Maripier', 'F', 'Referee', 'Basketball');
INSERT INTO TechnicalOfficials VALUES('1963920', 'MAZZONI Manuel', 'M', 'Referee', 'Basketball');
INSERT INTO TechnicalOfficials VALUES('1969254', 'LATOS Maria', 'F', 'Referee', 'Rugby Sevens');
INSERT INTO TechnicalOfficials VALUES('1969255', 'FERREIRA Morne', 'M', 'Referee', 'Rugby Sevens');
INSERT INTO TechnicalOfficials VALUES('1969256', 'BREAKSPEAR Ben', 'M', 'Referee', 'Rugby Sevens');
INSERT INTO TechnicalOfficials VALUES('1969257', 'DUARTE Paulo', 'M', 'Referee', 'Rugby Sevens');
INSERT INTO TechnicalOfficials VALUES('1969258', 'WAY Jordan', 'M', 'Referee', 'Rugby Sevens');
INSERT INTO TechnicalOfficials VALUES('1969260', 'HOGAN Nick', 'M', 'Referee', 'Rugby Sevens');
INSERT INTO TechnicalOfficials VALUES('1969261', 'RACACA Lavenia', 'F', 'Referee', 'Rugby Sevens');
INSERT INTO TechnicalOfficials VALUES('1969262', 'CARTER Jennifer', 'F', 'Referee', 'Rugby Sevens');
INSERT INTO TechnicalOfficials VALUES('1969263', 'COGGER-ORR Maggie', 'F', 'Referee', 'Rugby Sevens');
INSERT INTO TechnicalOfficials VALUES('1969264', 'RODDEN Matt', 'M', 'Referee', 'Rugby Sevens');
INSERT INTO TechnicalOfficials VALUES('1969265', 'SELWOOD George', 'M', 'Referee', 'Rugby Sevens');
INSERT INTO TechnicalOfficials VALUES('1969266', 'LOPEZ Cisco', 'M', 'Referee', 'Rugby Sevens');
INSERT INTO TechnicalOfficials VALUES('1969267', 'KUWAI Ano', 'F', 'Referee', 'Rugby Sevens');
INSERT INTO TechnicalOfficials VALUES('1969268', 'LOOK Michelle', 'F', 'Referee', 'Rugby Sevens');
INSERT INTO TechnicalOfficials VALUES('1969271', 'GONZALEZ Francisco', 'M', 'Referee', 'Rugby Sevens');
INSERT INTO TechnicalOfficials VALUES('1969272', 'WATTERS Phil', 'M', 'Referee', 'Rugby Sevens');
INSERT INTO TechnicalOfficials VALUES('1969273', 'CHAUDHRY Talal-Azmat', 'M', 'Referee', 'Rugby Sevens');
INSERT INTO TechnicalOfficials VALUES('1969274', 'CHAN Craig', 'M', 'Referee', 'Rugby Sevens');
INSERT INTO TechnicalOfficials VALUES('1969278', 'BROWN Finlay', 'M', 'Referee', 'Rugby Sevens');
INSERT INTO TechnicalOfficials VALUES('1969280', 'ROCHE Kat', 'F', 'Referee', 'Rugby Sevens');
INSERT INTO TechnicalOfficials VALUES('1969282', 'ARCHER Jamie', 'M', 'Referee', 'Rugby Sevens');
INSERT INTO TechnicalOfficials VALUES('1969286', 'JACOBS Aj', 'M', 'Referee', 'Rugby Sevens');
INSERT INTO TechnicalOfficials VALUES('1972217', 'GURBANALIYEV Emil', 'M', 'Referee', 'Boxing');
INSERT INTO TechnicalOfficials VALUES('1972380', 'MILAN PONCE Juan', 'M', 'Judge', 'Boxing');
INSERT INTO TechnicalOfficials VALUES('1978063', 'RAMOS Armando', 'M', 'Referee', 'Basketball');
INSERT INTO TechnicalOfficials VALUES('1978746', 'JULIEN Chantal', 'F', 'Referee', 'Basketball');
INSERT INTO TechnicalOfficials VALUES('1979320', 'PALVANOV Alisher', 'M', 'Referee', 'Boxing');
INSERT INTO TechnicalOfficials VALUES('1979476', 'MUHIDDINOV Mansur', 'M', 'Judge', 'Boxing');
INSERT INTO TechnicalOfficials VALUES('1979504', 'DROZ Nicolas', 'M', 'Judge', 'Skateboarding');
INSERT INTO TechnicalOfficials VALUES('1979546', 'JUMANIYAZOV Bahodir', 'M', 'Judge', 'Boxing');
INSERT INTO TechnicalOfficials VALUES('1984366', 'KEANE Reuben', 'M', 'Referee', 'Rugby Sevens');
INSERT INTO TechnicalOfficials VALUES('1984367', 'MILLER Tyler', 'F', 'Referee', 'Rugby Sevens');
INSERT INTO TechnicalOfficials VALUES('1986901', 'LEE Jaewook', 'M', 'Referee', 'Taekwondo');
INSERT INTO TechnicalOfficials VALUES('1988167', 'MGBILITY', 'M', 'Head Judge', 'Breaking');
INSERT INTO TechnicalOfficials VALUES('1990684', 'CHIAMPAS George', 'M', 'Referee', 'Football');
INSERT INTO TechnicalOfficials VALUES('1990685', 'DUEHMERT Katharina', 'F', 'Referee', 'Football');
INSERT INTO TechnicalOfficials VALUES('1990686', 'FEKE Penateti', 'F', 'Referee', 'Football');
INSERT INTO TechnicalOfficials VALUES('1990687', 'FUSTAGNO Fiorella', 'F', 'Referee', 'Football');
INSERT INTO TechnicalOfficials VALUES('1990688', 'TERRA Tadeu', 'M', 'Referee', 'Football');
INSERT INTO TechnicalOfficials VALUES('1990690', 'BILLINGHAM Johsan', 'M', 'Referee', 'Football');
INSERT INTO TechnicalOfficials VALUES('1990691', 'BOYCE Steve', 'M', 'Referee', 'Football');
INSERT INTO TechnicalOfficials VALUES('1990692', 'CARPINTEIRO ZIMMERMANN Philip', 'M', 'Referee', 'Football');
INSERT INTO TechnicalOfficials VALUES('1990693', 'DEAN Pauline', 'F', 'Referee', 'Football');
INSERT INTO TechnicalOfficials VALUES('1990695', 'ARAUJO Joao', 'M', 'Referee', 'Football');
INSERT INTO TechnicalOfficials VALUES('1990697', 'FOFI Lorenzo', 'M', 'Referee', 'Football');
INSERT INTO TechnicalOfficials VALUES('1990698', 'HAMARSHA Zeina', 'F', 'Referee', 'Football');
INSERT INTO TechnicalOfficials VALUES('1990700', 'ILIC James', 'M', 'Referee', 'Football');
INSERT INTO TechnicalOfficials VALUES('1990702', 'LEE Jae', 'M', 'Referee', 'Football');
INSERT INTO TechnicalOfficials VALUES('1990703', 'LENA Felix', 'M', 'Referee', 'Football');
INSERT INTO TechnicalOfficials VALUES('1990704', 'MACLEAN John', 'M', 'Referee', 'Football');
INSERT INTO TechnicalOfficials VALUES('1990705', 'MATEOS Andres', 'M', 'Referee', 'Football');
INSERT INTO TechnicalOfficials VALUES('1990706', 'MERZOUK Mehdi', 'M', 'Referee', 'Football');
INSERT INTO TechnicalOfficials VALUES('1990707', 'PATEL Sameer', 'M', 'Referee', 'Football');
INSERT INTO TechnicalOfficials VALUES('1990710', 'SCHEPERBOER Coen', 'M', 'Referee', 'Football');
INSERT INTO TechnicalOfficials VALUES('1990711', 'SHENOUDA Emad', 'M', 'Referee', 'Football');
INSERT INTO TechnicalOfficials VALUES('1990714', 'TOBIAS Guillermo', 'M', 'Referee', 'Football');
INSERT INTO TechnicalOfficials VALUES('1990715', 'UCHIDA Shintaro', 'M', 'Referee', 'Football');
INSERT INTO TechnicalOfficials VALUES('1990716', 'VELASQUEZ Pedro', 'M', 'Referee', 'Football');
INSERT INTO TechnicalOfficials VALUES('1990717', 'WEILER Richard', 'M', 'Referee', 'Football');
INSERT INTO TechnicalOfficials VALUES('1990718', 'TAVARES Eduardo', 'M', 'Referee', 'Football');
INSERT INTO TechnicalOfficials VALUES('1990719', 'DAI Jessie', 'F', 'Referee', 'Football');
INSERT INTO TechnicalOfficials VALUES('1990720', 'LUZANOV Pavel', 'M', 'Referee', 'Football');
INSERT INTO TechnicalOfficials VALUES('1990721', 'NASSAR Khaled', 'M', 'Referee', 'Football');
INSERT INTO TechnicalOfficials VALUES('1990736', 'DACOSTA Latoya', 'F', 'Referee', 'Football');
INSERT INTO TechnicalOfficials VALUES('1990795', 'MUKAI Naoko', 'F', 'Judge', '"Artistic Gymnastics');
INSERT INTO TechnicalOfficials VALUES('1990866', 'CACHEMAILLE Celine', 'F', 'Judge', '"Artistic Gymnastics');
INSERT INTO TechnicalOfficials VALUES('1990867', 'DETRAZ Stephane', 'M', 'Judge', '"Artistic Gymnastics');
INSERT INTO TechnicalOfficials VALUES('1990868', 'MARTINET Sylvie', 'F', 'Judge', '"Artistic Gymnastics');
INSERT INTO TechnicalOfficials VALUES('1990869', 'VINAGRE Rui', 'M', 'Judge', '"Artistic Gymnastics');
INSERT INTO TechnicalOfficials VALUES('1990870', 'TERRIER Zina', 'F', 'Judge', '"Artistic Gymnastics');
INSERT INTO TechnicalOfficials VALUES('1991692', 'SEN Levent', 'M', 'Referee', 'Wrestling');
INSERT INTO TechnicalOfficials VALUES('1991697', 'HALAWA Sherif', 'M', 'Referee', 'Wrestling');
INSERT INTO TechnicalOfficials VALUES('1991704', 'TRAI Belkacem', 'M', 'Referee', 'Wrestling');
INSERT INTO TechnicalOfficials VALUES('1993466', 'BASTIAN Beatrice', 'F', 'Judge', 'Boxing');
INSERT INTO TechnicalOfficials VALUES('1993467', 'BECKLES James', 'M', 'Judge', 'Boxing');
INSERT INTO TechnicalOfficials VALUES('1993468', 'BILETSKYI Igor', 'M', 'Judge', 'Boxing');
INSERT INTO TechnicalOfficials VALUES('1993469', 'CELEA Cristian-Georgica', 'M', 'Judge', 'Boxing');
INSERT INTO TechnicalOfficials VALUES('1993470', 'COBZAC Ramona Manuela', 'F', 'Judge', 'Boxing');
INSERT INTO TechnicalOfficials VALUES('1993544', 'SANKO Barbara', 'F', 'Judge', 'Boxing');
INSERT INTO TechnicalOfficials VALUES('1993545', 'FISCHER Angelika', 'F', 'Judge', 'Boxing');
INSERT INTO TechnicalOfficials VALUES('1993546', 'DREKE Erich', 'M', 'Judge', 'Boxing');
INSERT INTO TechnicalOfficials VALUES('1993547', 'EMERY Doug', 'M', 'Judge', 'Boxing');
INSERT INTO TechnicalOfficials VALUES('1993548', 'MORLEY Ray', 'M', 'Judge', 'Boxing');
INSERT INTO TechnicalOfficials VALUES('1993549', 'SALVO Hernan', 'M', 'Judge', 'Boxing');
INSERT INTO TechnicalOfficials VALUES('1993550', 'SANCHEZ Armando', 'M', 'Judge', 'Boxing');
INSERT INTO TechnicalOfficials VALUES('1993551', 'SANTI Bernardino', 'M', 'Judge', 'Boxing');
INSERT INTO TechnicalOfficials VALUES('1993552', 'SCAPPA Chiara', 'F', 'Judge', 'Boxing');
INSERT INTO TechnicalOfficials VALUES('1993553', 'SHEVELOVA Olha', 'F', 'Judge', 'Boxing');
INSERT INTO TechnicalOfficials VALUES('1993554', 'SHTYFURA Polina', 'F', 'Judge', 'Boxing');
INSERT INTO TechnicalOfficials VALUES('1993555', 'SOTO Andrews L', 'M', 'Judge', 'Boxing');
INSERT INTO TechnicalOfficials VALUES('1993556', 'TRIKALIOTIS Panagiotis', 'M', 'Judge', 'Boxing');
INSERT INTO TechnicalOfficials VALUES('1993557', 'VILLARREAL Angel Luis', 'M', 'Judge', 'Boxing');
INSERT INTO TechnicalOfficials VALUES('1993558', 'WONG William Alexander', 'M', 'Judge', 'Boxing');
INSERT INTO TechnicalOfficials VALUES('1993629', 'DAWANI Nadin', 'F', 'Referee', 'Taekwondo');
INSERT INTO TechnicalOfficials VALUES('1994107', 'RAVEL Stephanie', 'F', 'Judge', 'Boxing');
INSERT INTO TechnicalOfficials VALUES('1994108', 'MENARA Mario', 'M', 'Judge', 'Boxing');
INSERT INTO TechnicalOfficials VALUES('1994109', 'HADJRI Mokhtar', 'M', 'Judge', 'Boxing');
INSERT INTO TechnicalOfficials VALUES('1994110', 'GOSSELIN Severine', 'F', 'Judge', 'Boxing');
INSERT INTO TechnicalOfficials VALUES('1994111', 'SILBERMANN Philippe', 'M', 'Judge', 'Boxing');
INSERT INTO TechnicalOfficials VALUES('1994112', 'OUBAALI S Mail', 'M', 'Judge', 'Boxing');
INSERT INTO TechnicalOfficials VALUES('1994151', 'GUILLEMOT Vincent', 'M', 'Referee', 'Handball');
INSERT INTO TechnicalOfficials VALUES('1994152', 'LEFORT Yohan', 'M', 'Referee', 'Handball');
INSERT INTO TechnicalOfficials VALUES('1994153', 'CASTAGNO Frederic', 'M', 'Referee', 'Handball');
INSERT INTO TechnicalOfficials VALUES('1994154', 'GRUMEL Nicolas', 'M', 'Referee', 'Handball');
INSERT INTO TechnicalOfficials VALUES('1994155', 'RICHEL Marie', 'F', 'Referee', 'Handball');
INSERT INTO TechnicalOfficials VALUES('1994156', 'VINCENT Tatiana', 'F', 'Referee', 'Handball');
INSERT INTO TechnicalOfficials VALUES('1994157', 'PRUDHOMME Eddy', 'M', 'Referee', 'Handball');
INSERT INTO TechnicalOfficials VALUES('1994158', 'LAMY Jacques', 'M', 'Referee', 'Handball');
INSERT INTO TechnicalOfficials VALUES('1994159', 'RENAULT Romain', 'M', 'Referee', 'Handball');
INSERT INTO TechnicalOfficials VALUES('1994160', 'de la CROIX Marie Laure', 'F', 'Referee', 'Handball');
INSERT INTO TechnicalOfficials VALUES('1994161', 'NOUVEL Jerome', 'M', 'Referee', 'Handball');
INSERT INTO TechnicalOfficials VALUES('1994162', 'BENRHAZAL Mohamed', 'M', 'Referee', 'Handball');
INSERT INTO TechnicalOfficials VALUES('1994163', 'SMITS Nathalie', 'F', 'Referee', 'Handball');
INSERT INTO TechnicalOfficials VALUES('1994164', 'CARON Christophe', 'M', 'Referee', 'Handball');
INSERT INTO TechnicalOfficials VALUES('1994165', 'FERRIER Eduardo', 'M', 'Referee', 'Handball');
INSERT INTO TechnicalOfficials VALUES('1994166', 'EL MEDIOUNI Najet', 'F', 'Referee', 'Handball');
INSERT INTO TechnicalOfficials VALUES('1994167', 'VAILLANT Patrice', 'M', 'Referee', 'Handball');
INSERT INTO TechnicalOfficials VALUES('1994168', 'CALLIGARIS Laurent', 'M', 'Referee', 'Handball');
INSERT INTO TechnicalOfficials VALUES('1994169', 'CALLIGARIS Florian', 'M', 'Referee', 'Handball');
INSERT INTO TechnicalOfficials VALUES('1994170', 'VERCHERE Thomas', 'M', 'Referee', 'Handball');
INSERT INTO TechnicalOfficials VALUES('1994171', 'THOMAZO Alann', 'M', 'Referee', 'Handball');
INSERT INTO TechnicalOfficials VALUES('1994172', 'LEIDWANGER Stephane', 'M', 'Referee', 'Handball');
INSERT INTO TechnicalOfficials VALUES('1994173', 'BOBIN Thierry', 'M', 'Referee', 'Handball');
INSERT INTO TechnicalOfficials VALUES('1994174', 'SOBOLEWSKI Detlef', 'M', 'Referee', 'Handball');
INSERT INTO TechnicalOfficials VALUES('1994175', 'VERNET Gauthier', 'M', 'Referee', 'Handball');
INSERT INTO TechnicalOfficials VALUES('1994177', 'DAVID Audrey', 'F', 'Referee', 'Handball');
INSERT INTO TechnicalOfficials VALUES('1994178', 'PICARD Sylvie', 'F', 'Referee', 'Handball');
INSERT INTO TechnicalOfficials VALUES('1994179', 'GRALL LEMAITRE Flore', 'F', 'Referee', 'Handball');
INSERT INTO TechnicalOfficials VALUES('1994180', 'ALMEIDA Manuel', 'M', 'Referee', 'Handball');
INSERT INTO TechnicalOfficials VALUES('1994181', 'COQUIN Johann', 'M', 'Referee', 'Handball');
INSERT INTO TechnicalOfficials VALUES('1994182', 'GANDON Maxime', 'M', 'Referee', 'Handball');
INSERT INTO TechnicalOfficials VALUES('1994183', 'CAPLIEZ Virginie', 'F', 'Referee', 'Handball');
INSERT INTO TechnicalOfficials VALUES('1994510', 'ABUJABER Iman', 'F', 'Referee', 'Football');
INSERT INTO TechnicalOfficials VALUES('1995222', 'MEARY Aurelia', 'F', 'Referee', '3x3 Basketball');
INSERT INTO TechnicalOfficials VALUES('1995226', 'BOIRE Elise', 'F', 'Referee', '3x3 Basketball');
INSERT INTO TechnicalOfficials VALUES('1995228', 'BOUTONNET Gregoire', 'M', 'Referee', '3x3 Basketball');
INSERT INTO TechnicalOfficials VALUES('1995229', 'PREL Nicolas', 'M', 'Referee', '3x3 Basketball');
INSERT INTO TechnicalOfficials VALUES('1995231', 'TAEYE Corinne', 'F', 'Referee', '3x3 Basketball');
INSERT INTO TechnicalOfficials VALUES('1995232', 'FAYS Francois', 'M', 'Referee', '3x3 Basketball');
INSERT INTO TechnicalOfficials VALUES('1995233', 'FOREST Alexis', 'M', 'Referee', '3x3 Basketball');
INSERT INTO TechnicalOfficials VALUES('1995236', 'MECHIN Celine', 'F', 'Referee', '3x3 Basketball');
INSERT INTO TechnicalOfficials VALUES('1995237', 'SEVAUX Arnaud', 'M', 'Referee', '3x3 Basketball');
INSERT INTO TechnicalOfficials VALUES('1995239', 'CORTINOVIS BEGLOT Chloe', 'F', 'Referee', '3x3 Basketball');
INSERT INTO TechnicalOfficials VALUES('1995240', 'HENON Sandrine', 'F', 'Referee', '3x3 Basketball');
INSERT INTO TechnicalOfficials VALUES('1995244', 'FRANCOIS Cedric', 'M', 'Referee', '3x3 Basketball');
INSERT INTO TechnicalOfficials VALUES('1997639', 'FROST', 'F', 'Judge B', 'Breaking');
INSERT INTO TechnicalOfficials VALUES('1997650', 'DOM-K', 'M', 'Judge H', 'Breaking');
INSERT INTO TechnicalOfficials VALUES('1997675', 'JESS', 'F', 'Judge E', 'Breaking');
INSERT INTO TechnicalOfficials VALUES('1997676', 'INTACT', 'M', 'Judge I', 'Breaking');
INSERT INTO TechnicalOfficials VALUES('1998243', 'MIGAZ', 'M', 'Judge D', 'Breaking');
INSERT INTO TechnicalOfficials VALUES('2003348', 'VIRUS', 'M', 'Judge G', 'Breaking');
INSERT INTO TechnicalOfficials VALUES('2005147', 'ABATTI Ramon', 'M', 'Referee', 'Football');
INSERT INTO TechnicalOfficials VALUES('2005151', 'AL NAQBI Adel', 'M', 'Referee', 'Football');
INSERT INTO TechnicalOfficials VALUES('2005153', 'ALVES Edina', 'F', 'Referee', 'Football');
INSERT INTO TechnicalOfficials VALUES('2005159', 'BEIDA Dahane', 'M', 'Referee', 'Football');
INSERT INTO TechnicalOfficials VALUES('2005161', 'BERNATSKAIA Veronika', 'F', 'Referee', 'Football');
INSERT INTO TechnicalOfficials VALUES('2005166', 'CALDERAS Emikar', 'F', 'Referee', 'Football');
INSERT INTO TechnicalOfficials VALUES('2005170', 'CVETKOVIC Jelena', 'F', 'Referee', 'Football');
INSERT INTO TechnicalOfficials VALUES('2005179', 'ESKAS Espen', 'M', 'Referee', 'Football');
INSERT INTO TechnicalOfficials VALUES('2005180', 'FALCON Yael', 'M', 'Referee', 'Football');
INSERT INTO TechnicalOfficials VALUES('2005181', 'FERNANDEZ Anahi', 'F', 'Referee', 'Football');
INSERT INTO TechnicalOfficials VALUES('2005182', 'FISCHER Drew', 'M', 'Referee', 'Football');
INSERT INTO TechnicalOfficials VALUES('2005183', 'GARCIA Katia', 'F', 'Referee', 'Football');
INSERT INTO TechnicalOfficials VALUES('2005188', 'KARBOUBI Bouchra', 'F', 'Referee', 'Football');
INSERT INTO TechnicalOfficials VALUES('2005189', 'KAWANA-WAUGH Campbell-Kirk', 'M', 'Referee', 'Football');
INSERT INTO TechnicalOfficials VALUES('2005190', 'KIM Yujeong', 'F', 'Referee', 'Football');
INSERT INTO TechnicalOfficials VALUES('2005191', 'KLARLUND Frida', 'F', 'Referee', 'Football');
INSERT INTO TechnicalOfficials VALUES('2005193', 'LETEXIER Francois', 'M', 'Referee', 'Football');
INSERT INTO TechnicalOfficials VALUES('2005195', 'MARTINEZ Said', 'M', 'Referee', 'Football');
INSERT INTO TechnicalOfficials VALUES('2005200', 'NYBERG Glenn', 'M', 'Referee', 'Football');
INSERT INTO TechnicalOfficials VALUES('2005201', 'OLOFSSON Tess', 'F', 'Referee', 'Football');
INSERT INTO TechnicalOfficials VALUES('2005206', 'PENSO Tori', 'F', 'Referee', 'Football');
INSERT INTO TechnicalOfficials VALUES('2005218', 'WELCH Rebecca', 'F', 'Referee', 'Football');
INSERT INTO TechnicalOfficials VALUES('2005219', 'YAMASHITA Yoshimi', 'F', 'Referee', 'Football');
INSERT INTO TechnicalOfficials VALUES('2005674', 'LAUKKANEN Anna', 'F', 'Judge', 'Boxing');
INSERT INTO TechnicalOfficials VALUES('2005675', 'WILSON Rosalind', 'F', 'Judge', 'Boxing');
INSERT INTO TechnicalOfficials VALUES('2005676', 'MACDIARMADA Diarmuid', 'M', 'Judge', 'Boxing');